/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EnvelopedClient type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvelopedClient{}

// EnvelopedClient struct for EnvelopedClient
type EnvelopedClient struct {
	Item *Client `json:"item,omitempty"`
}

// NewEnvelopedClient instantiates a new EnvelopedClient object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvelopedClient() *EnvelopedClient {
	this := EnvelopedClient{}
	return &this
}

// NewEnvelopedClientWithDefaults instantiates a new EnvelopedClient object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvelopedClientWithDefaults() *EnvelopedClient {
	this := EnvelopedClient{}
	return &this
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *EnvelopedClient) GetItem() Client {
	if o == nil || IsNil(o.Item) {
		var ret Client
		return ret
	}
	return *o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvelopedClient) GetItemOk() (*Client, bool) {
	if o == nil || IsNil(o.Item) {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *EnvelopedClient) HasItem() bool {
	if o != nil && !IsNil(o.Item) {
		return true
	}

	return false
}

// SetItem gets a reference to the given Client and assigns it to the Item field.
func (o *EnvelopedClient) SetItem(v Client) {
	o.Item = &v
}

func (o EnvelopedClient) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvelopedClient) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Item) {
		toSerialize["item"] = o.Item
	}
	return toSerialize, nil
}

type NullableEnvelopedClient struct {
	value *EnvelopedClient
	isSet bool
}

func (v NullableEnvelopedClient) Get() *EnvelopedClient {
	return v.value
}

func (v *NullableEnvelopedClient) Set(val *EnvelopedClient) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvelopedClient) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvelopedClient) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvelopedClient(val *EnvelopedClient) *NullableEnvelopedClient {
	return &NullableEnvelopedClient{value: val, isSet: true}
}

func (v NullableEnvelopedClient) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvelopedClient) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


