/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// RequestNewMFAOTPCodeRequest - struct for RequestNewMFAOTPCodeRequest
type RequestNewMFAOTPCodeRequest struct {
	MFAConfigResendEmail *MFAConfigResendEmail
	MFAConfigResendSMS *MFAConfigResendSMS
}

// MFAConfigResendEmailAsRequestNewMFAOTPCodeRequest is a convenience function that returns MFAConfigResendEmail wrapped in RequestNewMFAOTPCodeRequest
func MFAConfigResendEmailAsRequestNewMFAOTPCodeRequest(v *MFAConfigResendEmail) RequestNewMFAOTPCodeRequest {
	return RequestNewMFAOTPCodeRequest{
		MFAConfigResendEmail: v,
	}
}

// MFAConfigResendSMSAsRequestNewMFAOTPCodeRequest is a convenience function that returns MFAConfigResendSMS wrapped in RequestNewMFAOTPCodeRequest
func MFAConfigResendSMSAsRequestNewMFAOTPCodeRequest(v *MFAConfigResendSMS) RequestNewMFAOTPCodeRequest {
	return RequestNewMFAOTPCodeRequest{
		MFAConfigResendSMS: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *RequestNewMFAOTPCodeRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into MFAConfigResendEmail
	err = newStrictDecoder(data).Decode(&dst.MFAConfigResendEmail)
	if err == nil {
		jsonMFAConfigResendEmail, _ := json.Marshal(dst.MFAConfigResendEmail)
		if string(jsonMFAConfigResendEmail) == "{}" { // empty struct
			dst.MFAConfigResendEmail = nil
		} else {
			if err = validator.Validate(dst.MFAConfigResendEmail); err != nil {
				dst.MFAConfigResendEmail = nil
			} else {
				match++
			}
		}
	} else {
		dst.MFAConfigResendEmail = nil
	}

	// try to unmarshal data into MFAConfigResendSMS
	err = newStrictDecoder(data).Decode(&dst.MFAConfigResendSMS)
	if err == nil {
		jsonMFAConfigResendSMS, _ := json.Marshal(dst.MFAConfigResendSMS)
		if string(jsonMFAConfigResendSMS) == "{}" { // empty struct
			dst.MFAConfigResendSMS = nil
		} else {
			if err = validator.Validate(dst.MFAConfigResendSMS); err != nil {
				dst.MFAConfigResendSMS = nil
			} else {
				match++
			}
		}
	} else {
		dst.MFAConfigResendSMS = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.MFAConfigResendEmail = nil
		dst.MFAConfigResendSMS = nil

		return fmt.Errorf("data matches more than one schema in oneOf(RequestNewMFAOTPCodeRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(RequestNewMFAOTPCodeRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RequestNewMFAOTPCodeRequest) MarshalJSON() ([]byte, error) {
	if src.MFAConfigResendEmail != nil {
		return json.Marshal(&src.MFAConfigResendEmail)
	}

	if src.MFAConfigResendSMS != nil {
		return json.Marshal(&src.MFAConfigResendSMS)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *RequestNewMFAOTPCodeRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.MFAConfigResendEmail != nil {
		return obj.MFAConfigResendEmail
	}

	if obj.MFAConfigResendSMS != nil {
		return obj.MFAConfigResendSMS
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj RequestNewMFAOTPCodeRequest) GetActualInstanceValue() (interface{}) {
	if obj.MFAConfigResendEmail != nil {
		return *obj.MFAConfigResendEmail
	}

	if obj.MFAConfigResendSMS != nil {
		return *obj.MFAConfigResendSMS
	}

	// all schemas are nil
	return nil
}

type NullableRequestNewMFAOTPCodeRequest struct {
	value *RequestNewMFAOTPCodeRequest
	isSet bool
}

func (v NullableRequestNewMFAOTPCodeRequest) Get() *RequestNewMFAOTPCodeRequest {
	return v.value
}

func (v *NullableRequestNewMFAOTPCodeRequest) Set(val *RequestNewMFAOTPCodeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestNewMFAOTPCodeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestNewMFAOTPCodeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestNewMFAOTPCodeRequest(val *RequestNewMFAOTPCodeRequest) *NullableRequestNewMFAOTPCodeRequest {
	return &NullableRequestNewMFAOTPCodeRequest{value: val, isSet: true}
}

func (v NullableRequestNewMFAOTPCodeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestNewMFAOTPCodeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


