/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ValidateMFAConfigUpdateRequest - struct for ValidateMFAConfigUpdateRequest
type ValidateMFAConfigUpdateRequest struct {
	MFAConfigValidationEmail *MFAConfigValidationEmail
	MFAConfigValidationSMS *MFAConfigValidationSMS
	MFAConfigValidationTOTP *MFAConfigValidationTOTP
}

// MFAConfigValidationEmailAsValidateMFAConfigUpdateRequest is a convenience function that returns MFAConfigValidationEmail wrapped in ValidateMFAConfigUpdateRequest
func MFAConfigValidationEmailAsValidateMFAConfigUpdateRequest(v *MFAConfigValidationEmail) ValidateMFAConfigUpdateRequest {
	return ValidateMFAConfigUpdateRequest{
		MFAConfigValidationEmail: v,
	}
}

// MFAConfigValidationSMSAsValidateMFAConfigUpdateRequest is a convenience function that returns MFAConfigValidationSMS wrapped in ValidateMFAConfigUpdateRequest
func MFAConfigValidationSMSAsValidateMFAConfigUpdateRequest(v *MFAConfigValidationSMS) ValidateMFAConfigUpdateRequest {
	return ValidateMFAConfigUpdateRequest{
		MFAConfigValidationSMS: v,
	}
}

// MFAConfigValidationTOTPAsValidateMFAConfigUpdateRequest is a convenience function that returns MFAConfigValidationTOTP wrapped in ValidateMFAConfigUpdateRequest
func MFAConfigValidationTOTPAsValidateMFAConfigUpdateRequest(v *MFAConfigValidationTOTP) ValidateMFAConfigUpdateRequest {
	return ValidateMFAConfigUpdateRequest{
		MFAConfigValidationTOTP: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ValidateMFAConfigUpdateRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into MFAConfigValidationEmail
	err = newStrictDecoder(data).Decode(&dst.MFAConfigValidationEmail)
	if err == nil {
		jsonMFAConfigValidationEmail, _ := json.Marshal(dst.MFAConfigValidationEmail)
		if string(jsonMFAConfigValidationEmail) == "{}" { // empty struct
			dst.MFAConfigValidationEmail = nil
		} else {
			if err = validator.Validate(dst.MFAConfigValidationEmail); err != nil {
				dst.MFAConfigValidationEmail = nil
			} else {
				match++
			}
		}
	} else {
		dst.MFAConfigValidationEmail = nil
	}

	// try to unmarshal data into MFAConfigValidationSMS
	err = newStrictDecoder(data).Decode(&dst.MFAConfigValidationSMS)
	if err == nil {
		jsonMFAConfigValidationSMS, _ := json.Marshal(dst.MFAConfigValidationSMS)
		if string(jsonMFAConfigValidationSMS) == "{}" { // empty struct
			dst.MFAConfigValidationSMS = nil
		} else {
			if err = validator.Validate(dst.MFAConfigValidationSMS); err != nil {
				dst.MFAConfigValidationSMS = nil
			} else {
				match++
			}
		}
	} else {
		dst.MFAConfigValidationSMS = nil
	}

	// try to unmarshal data into MFAConfigValidationTOTP
	err = newStrictDecoder(data).Decode(&dst.MFAConfigValidationTOTP)
	if err == nil {
		jsonMFAConfigValidationTOTP, _ := json.Marshal(dst.MFAConfigValidationTOTP)
		if string(jsonMFAConfigValidationTOTP) == "{}" { // empty struct
			dst.MFAConfigValidationTOTP = nil
		} else {
			if err = validator.Validate(dst.MFAConfigValidationTOTP); err != nil {
				dst.MFAConfigValidationTOTP = nil
			} else {
				match++
			}
		}
	} else {
		dst.MFAConfigValidationTOTP = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.MFAConfigValidationEmail = nil
		dst.MFAConfigValidationSMS = nil
		dst.MFAConfigValidationTOTP = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ValidateMFAConfigUpdateRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ValidateMFAConfigUpdateRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ValidateMFAConfigUpdateRequest) MarshalJSON() ([]byte, error) {
	if src.MFAConfigValidationEmail != nil {
		return json.Marshal(&src.MFAConfigValidationEmail)
	}

	if src.MFAConfigValidationSMS != nil {
		return json.Marshal(&src.MFAConfigValidationSMS)
	}

	if src.MFAConfigValidationTOTP != nil {
		return json.Marshal(&src.MFAConfigValidationTOTP)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ValidateMFAConfigUpdateRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.MFAConfigValidationEmail != nil {
		return obj.MFAConfigValidationEmail
	}

	if obj.MFAConfigValidationSMS != nil {
		return obj.MFAConfigValidationSMS
	}

	if obj.MFAConfigValidationTOTP != nil {
		return obj.MFAConfigValidationTOTP
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ValidateMFAConfigUpdateRequest) GetActualInstanceValue() (interface{}) {
	if obj.MFAConfigValidationEmail != nil {
		return *obj.MFAConfigValidationEmail
	}

	if obj.MFAConfigValidationSMS != nil {
		return *obj.MFAConfigValidationSMS
	}

	if obj.MFAConfigValidationTOTP != nil {
		return *obj.MFAConfigValidationTOTP
	}

	// all schemas are nil
	return nil
}

type NullableValidateMFAConfigUpdateRequest struct {
	value *ValidateMFAConfigUpdateRequest
	isSet bool
}

func (v NullableValidateMFAConfigUpdateRequest) Get() *ValidateMFAConfigUpdateRequest {
	return v.value
}

func (v *NullableValidateMFAConfigUpdateRequest) Set(val *ValidateMFAConfigUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableValidateMFAConfigUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableValidateMFAConfigUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidateMFAConfigUpdateRequest(val *ValidateMFAConfigUpdateRequest) *NullableValidateMFAConfigUpdateRequest {
	return &NullableValidateMFAConfigUpdateRequest{value: val, isSet: true}
}

func (v NullableValidateMFAConfigUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidateMFAConfigUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


