/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// StopKind the model 'StopKind'
type StopKind string

// List of StopKind
const (
	STOPKIND_PICKUP StopKind = "pickup"
	STOPKIND_DELIVERY StopKind = "delivery"
	STOPKIND_ACKNOWLEDGEMENT StopKind = "acknowledgement"
)

// All allowed values of StopKind enum
var AllowedStopKindEnumValues = []StopKind{
	"pickup",
	"delivery",
	"acknowledgement",
}

func (v *StopKind) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := StopKind(value)
	for _, existing := range AllowedStopKindEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid StopKind", value)
}

// NewStopKindFromValue returns a pointer to a valid StopKind
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewStopKindFromValue(v string) (*StopKind, error) {
	ev := StopKind(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for StopKind: valid values are %v", v, AllowedStopKindEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v StopKind) IsValid() bool {
	for _, existing := range AllowedStopKindEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to StopKind value
func (v StopKind) Ptr() *StopKind {
	return &v
}

type NullableStopKind struct {
	value *StopKind
	isSet bool
}

func (v NullableStopKind) Get() *StopKind {
	return v.value
}

func (v *NullableStopKind) Set(val *StopKind) {
	v.value = val
	v.isSet = true
}

func (v NullableStopKind) IsSet() bool {
	return v.isSet
}

func (v *NullableStopKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStopKind(val *StopKind) *NullableStopKind {
	return &NullableStopKind{value: val, isSet: true}
}

func (v NullableStopKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStopKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

