/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TravelDurationSlidingBreak type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TravelDurationSlidingBreak{}

// TravelDurationSlidingBreak Limitation rule on max travel duration without any break.
type TravelDurationSlidingBreak struct {
	Type string `json:"type"`
	// A period of time, expressed in the ISO8601 **duration** format.
	MinBreakDuration string `json:"minBreakDuration" validate:"regexp=^P(\\\\d+Y)?(\\\\d+M)?(\\\\d+W)?(\\\\d+D)?(T(\\\\d+H)?(\\\\d+M)?(\\\\d+S)?)?$"`
	// A period of time, expressed in the ISO8601 **duration** format.
	MaxInterBreakDuration string `json:"maxInterBreakDuration" validate:"regexp=^P(\\\\d+Y)?(\\\\d+M)?(\\\\d+W)?(\\\\d+D)?(T(\\\\d+H)?(\\\\d+M)?(\\\\d+S)?)?$"`
}

type _TravelDurationSlidingBreak TravelDurationSlidingBreak

// NewTravelDurationSlidingBreak instantiates a new TravelDurationSlidingBreak object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTravelDurationSlidingBreak(type_ string, minBreakDuration string, maxInterBreakDuration string) *TravelDurationSlidingBreak {
	this := TravelDurationSlidingBreak{}
	this.Type = type_
	this.MinBreakDuration = minBreakDuration
	this.MaxInterBreakDuration = maxInterBreakDuration
	return &this
}

// NewTravelDurationSlidingBreakWithDefaults instantiates a new TravelDurationSlidingBreak object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTravelDurationSlidingBreakWithDefaults() *TravelDurationSlidingBreak {
	this := TravelDurationSlidingBreak{}
	return &this
}

// GetType returns the Type field value
func (o *TravelDurationSlidingBreak) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TravelDurationSlidingBreak) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TravelDurationSlidingBreak) SetType(v string) {
	o.Type = v
}

// GetMinBreakDuration returns the MinBreakDuration field value
func (o *TravelDurationSlidingBreak) GetMinBreakDuration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MinBreakDuration
}

// GetMinBreakDurationOk returns a tuple with the MinBreakDuration field value
// and a boolean to check if the value has been set.
func (o *TravelDurationSlidingBreak) GetMinBreakDurationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinBreakDuration, true
}

// SetMinBreakDuration sets field value
func (o *TravelDurationSlidingBreak) SetMinBreakDuration(v string) {
	o.MinBreakDuration = v
}

// GetMaxInterBreakDuration returns the MaxInterBreakDuration field value
func (o *TravelDurationSlidingBreak) GetMaxInterBreakDuration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MaxInterBreakDuration
}

// GetMaxInterBreakDurationOk returns a tuple with the MaxInterBreakDuration field value
// and a boolean to check if the value has been set.
func (o *TravelDurationSlidingBreak) GetMaxInterBreakDurationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxInterBreakDuration, true
}

// SetMaxInterBreakDuration sets field value
func (o *TravelDurationSlidingBreak) SetMaxInterBreakDuration(v string) {
	o.MaxInterBreakDuration = v
}

func (o TravelDurationSlidingBreak) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TravelDurationSlidingBreak) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["minBreakDuration"] = o.MinBreakDuration
	toSerialize["maxInterBreakDuration"] = o.MaxInterBreakDuration
	return toSerialize, nil
}

func (o *TravelDurationSlidingBreak) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"minBreakDuration",
		"maxInterBreakDuration",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTravelDurationSlidingBreak := _TravelDurationSlidingBreak{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTravelDurationSlidingBreak)

	if err != nil {
		return err
	}

	*o = TravelDurationSlidingBreak(varTravelDurationSlidingBreak)

	return err
}

type NullableTravelDurationSlidingBreak struct {
	value *TravelDurationSlidingBreak
	isSet bool
}

func (v NullableTravelDurationSlidingBreak) Get() *TravelDurationSlidingBreak {
	return v.value
}

func (v *NullableTravelDurationSlidingBreak) Set(val *TravelDurationSlidingBreak) {
	v.value = val
	v.isSet = true
}

func (v NullableTravelDurationSlidingBreak) IsSet() bool {
	return v.isSet
}

func (v *NullableTravelDurationSlidingBreak) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTravelDurationSlidingBreak(val *TravelDurationSlidingBreak) *NullableTravelDurationSlidingBreak {
	return &NullableTravelDurationSlidingBreak{value: val, isSet: true}
}

func (v NullableTravelDurationSlidingBreak) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTravelDurationSlidingBreak) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


