/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AdditionalConstraintRemovalStrategy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdditionalConstraintRemovalStrategy{}

// AdditionalConstraintRemovalStrategy If the tour does not respect the defined removal strategy, then the tour is invalid.
type AdditionalConstraintRemovalStrategy struct {
	Type string `json:"type"`
	Name *string `json:"name,omitempty"`
	ResourceTags []string `json:"resourceTags,omitempty"`
	Capacities []string `json:"capacities,omitempty"`
	RemovalStrategy *RemovalStrategyType `json:"removalStrategy,omitempty"`
}

type _AdditionalConstraintRemovalStrategy AdditionalConstraintRemovalStrategy

// NewAdditionalConstraintRemovalStrategy instantiates a new AdditionalConstraintRemovalStrategy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdditionalConstraintRemovalStrategy(type_ string) *AdditionalConstraintRemovalStrategy {
	this := AdditionalConstraintRemovalStrategy{}
	this.Type = type_
	return &this
}

// NewAdditionalConstraintRemovalStrategyWithDefaults instantiates a new AdditionalConstraintRemovalStrategy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdditionalConstraintRemovalStrategyWithDefaults() *AdditionalConstraintRemovalStrategy {
	this := AdditionalConstraintRemovalStrategy{}
	return &this
}

// GetType returns the Type field value
func (o *AdditionalConstraintRemovalStrategy) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AdditionalConstraintRemovalStrategy) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AdditionalConstraintRemovalStrategy) SetType(v string) {
	o.Type = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AdditionalConstraintRemovalStrategy) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdditionalConstraintRemovalStrategy) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AdditionalConstraintRemovalStrategy) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AdditionalConstraintRemovalStrategy) SetName(v string) {
	o.Name = &v
}

// GetResourceTags returns the ResourceTags field value if set, zero value otherwise.
func (o *AdditionalConstraintRemovalStrategy) GetResourceTags() []string {
	if o == nil || IsNil(o.ResourceTags) {
		var ret []string
		return ret
	}
	return o.ResourceTags
}

// GetResourceTagsOk returns a tuple with the ResourceTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdditionalConstraintRemovalStrategy) GetResourceTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.ResourceTags) {
		return nil, false
	}
	return o.ResourceTags, true
}

// HasResourceTags returns a boolean if a field has been set.
func (o *AdditionalConstraintRemovalStrategy) HasResourceTags() bool {
	if o != nil && !IsNil(o.ResourceTags) {
		return true
	}

	return false
}

// SetResourceTags gets a reference to the given []string and assigns it to the ResourceTags field.
func (o *AdditionalConstraintRemovalStrategy) SetResourceTags(v []string) {
	o.ResourceTags = v
}

// GetCapacities returns the Capacities field value if set, zero value otherwise.
func (o *AdditionalConstraintRemovalStrategy) GetCapacities() []string {
	if o == nil || IsNil(o.Capacities) {
		var ret []string
		return ret
	}
	return o.Capacities
}

// GetCapacitiesOk returns a tuple with the Capacities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdditionalConstraintRemovalStrategy) GetCapacitiesOk() ([]string, bool) {
	if o == nil || IsNil(o.Capacities) {
		return nil, false
	}
	return o.Capacities, true
}

// HasCapacities returns a boolean if a field has been set.
func (o *AdditionalConstraintRemovalStrategy) HasCapacities() bool {
	if o != nil && !IsNil(o.Capacities) {
		return true
	}

	return false
}

// SetCapacities gets a reference to the given []string and assigns it to the Capacities field.
func (o *AdditionalConstraintRemovalStrategy) SetCapacities(v []string) {
	o.Capacities = v
}

// GetRemovalStrategy returns the RemovalStrategy field value if set, zero value otherwise.
func (o *AdditionalConstraintRemovalStrategy) GetRemovalStrategy() RemovalStrategyType {
	if o == nil || IsNil(o.RemovalStrategy) {
		var ret RemovalStrategyType
		return ret
	}
	return *o.RemovalStrategy
}

// GetRemovalStrategyOk returns a tuple with the RemovalStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdditionalConstraintRemovalStrategy) GetRemovalStrategyOk() (*RemovalStrategyType, bool) {
	if o == nil || IsNil(o.RemovalStrategy) {
		return nil, false
	}
	return o.RemovalStrategy, true
}

// HasRemovalStrategy returns a boolean if a field has been set.
func (o *AdditionalConstraintRemovalStrategy) HasRemovalStrategy() bool {
	if o != nil && !IsNil(o.RemovalStrategy) {
		return true
	}

	return false
}

// SetRemovalStrategy gets a reference to the given RemovalStrategyType and assigns it to the RemovalStrategy field.
func (o *AdditionalConstraintRemovalStrategy) SetRemovalStrategy(v RemovalStrategyType) {
	o.RemovalStrategy = &v
}

func (o AdditionalConstraintRemovalStrategy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdditionalConstraintRemovalStrategy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ResourceTags) {
		toSerialize["resourceTags"] = o.ResourceTags
	}
	if !IsNil(o.Capacities) {
		toSerialize["capacities"] = o.Capacities
	}
	if !IsNil(o.RemovalStrategy) {
		toSerialize["removalStrategy"] = o.RemovalStrategy
	}
	return toSerialize, nil
}

func (o *AdditionalConstraintRemovalStrategy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdditionalConstraintRemovalStrategy := _AdditionalConstraintRemovalStrategy{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdditionalConstraintRemovalStrategy)

	if err != nil {
		return err
	}

	*o = AdditionalConstraintRemovalStrategy(varAdditionalConstraintRemovalStrategy)

	return err
}

type NullableAdditionalConstraintRemovalStrategy struct {
	value *AdditionalConstraintRemovalStrategy
	isSet bool
}

func (v NullableAdditionalConstraintRemovalStrategy) Get() *AdditionalConstraintRemovalStrategy {
	return v.value
}

func (v *NullableAdditionalConstraintRemovalStrategy) Set(val *AdditionalConstraintRemovalStrategy) {
	v.value = val
	v.isSet = true
}

func (v NullableAdditionalConstraintRemovalStrategy) IsSet() bool {
	return v.isSet
}

func (v *NullableAdditionalConstraintRemovalStrategy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdditionalConstraintRemovalStrategy(val *AdditionalConstraintRemovalStrategy) *NullableAdditionalConstraintRemovalStrategy {
	return &NullableAdditionalConstraintRemovalStrategy{value: val, isSet: true}
}

func (v NullableAdditionalConstraintRemovalStrategy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdditionalConstraintRemovalStrategy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


