/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AdditionalConstraintAtLeastOneValidCapacity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdditionalConstraintAtLeastOneValidCapacity{}

// AdditionalConstraintAtLeastOneValidCapacity If the tour has not, at each stop, one of its capacities lower than or equal to the link limit, then the tour is invalid.
type AdditionalConstraintAtLeastOneValidCapacity struct {
	Type string `json:"type"`
	Name *string `json:"name,omitempty"`
	Capacities map[string]float32 `json:"capacities"`
	ResourceTags []string `json:"resourceTags,omitempty"`
}

type _AdditionalConstraintAtLeastOneValidCapacity AdditionalConstraintAtLeastOneValidCapacity

// NewAdditionalConstraintAtLeastOneValidCapacity instantiates a new AdditionalConstraintAtLeastOneValidCapacity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdditionalConstraintAtLeastOneValidCapacity(type_ string, capacities map[string]float32) *AdditionalConstraintAtLeastOneValidCapacity {
	this := AdditionalConstraintAtLeastOneValidCapacity{}
	this.Type = type_
	this.Capacities = capacities
	return &this
}

// NewAdditionalConstraintAtLeastOneValidCapacityWithDefaults instantiates a new AdditionalConstraintAtLeastOneValidCapacity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdditionalConstraintAtLeastOneValidCapacityWithDefaults() *AdditionalConstraintAtLeastOneValidCapacity {
	this := AdditionalConstraintAtLeastOneValidCapacity{}
	return &this
}

// GetType returns the Type field value
func (o *AdditionalConstraintAtLeastOneValidCapacity) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AdditionalConstraintAtLeastOneValidCapacity) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AdditionalConstraintAtLeastOneValidCapacity) SetType(v string) {
	o.Type = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AdditionalConstraintAtLeastOneValidCapacity) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdditionalConstraintAtLeastOneValidCapacity) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AdditionalConstraintAtLeastOneValidCapacity) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AdditionalConstraintAtLeastOneValidCapacity) SetName(v string) {
	o.Name = &v
}

// GetCapacities returns the Capacities field value
func (o *AdditionalConstraintAtLeastOneValidCapacity) GetCapacities() map[string]float32 {
	if o == nil {
		var ret map[string]float32
		return ret
	}

	return o.Capacities
}

// GetCapacitiesOk returns a tuple with the Capacities field value
// and a boolean to check if the value has been set.
func (o *AdditionalConstraintAtLeastOneValidCapacity) GetCapacitiesOk() (*map[string]float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Capacities, true
}

// SetCapacities sets field value
func (o *AdditionalConstraintAtLeastOneValidCapacity) SetCapacities(v map[string]float32) {
	o.Capacities = v
}

// GetResourceTags returns the ResourceTags field value if set, zero value otherwise.
func (o *AdditionalConstraintAtLeastOneValidCapacity) GetResourceTags() []string {
	if o == nil || IsNil(o.ResourceTags) {
		var ret []string
		return ret
	}
	return o.ResourceTags
}

// GetResourceTagsOk returns a tuple with the ResourceTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdditionalConstraintAtLeastOneValidCapacity) GetResourceTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.ResourceTags) {
		return nil, false
	}
	return o.ResourceTags, true
}

// HasResourceTags returns a boolean if a field has been set.
func (o *AdditionalConstraintAtLeastOneValidCapacity) HasResourceTags() bool {
	if o != nil && !IsNil(o.ResourceTags) {
		return true
	}

	return false
}

// SetResourceTags gets a reference to the given []string and assigns it to the ResourceTags field.
func (o *AdditionalConstraintAtLeastOneValidCapacity) SetResourceTags(v []string) {
	o.ResourceTags = v
}

func (o AdditionalConstraintAtLeastOneValidCapacity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdditionalConstraintAtLeastOneValidCapacity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["capacities"] = o.Capacities
	if !IsNil(o.ResourceTags) {
		toSerialize["resourceTags"] = o.ResourceTags
	}
	return toSerialize, nil
}

func (o *AdditionalConstraintAtLeastOneValidCapacity) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"capacities",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdditionalConstraintAtLeastOneValidCapacity := _AdditionalConstraintAtLeastOneValidCapacity{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdditionalConstraintAtLeastOneValidCapacity)

	if err != nil {
		return err
	}

	*o = AdditionalConstraintAtLeastOneValidCapacity(varAdditionalConstraintAtLeastOneValidCapacity)

	return err
}

type NullableAdditionalConstraintAtLeastOneValidCapacity struct {
	value *AdditionalConstraintAtLeastOneValidCapacity
	isSet bool
}

func (v NullableAdditionalConstraintAtLeastOneValidCapacity) Get() *AdditionalConstraintAtLeastOneValidCapacity {
	return v.value
}

func (v *NullableAdditionalConstraintAtLeastOneValidCapacity) Set(val *AdditionalConstraintAtLeastOneValidCapacity) {
	v.value = val
	v.isSet = true
}

func (v NullableAdditionalConstraintAtLeastOneValidCapacity) IsSet() bool {
	return v.isSet
}

func (v *NullableAdditionalConstraintAtLeastOneValidCapacity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdditionalConstraintAtLeastOneValidCapacity(val *AdditionalConstraintAtLeastOneValidCapacity) *NullableAdditionalConstraintAtLeastOneValidCapacity {
	return &NullableAdditionalConstraintAtLeastOneValidCapacity{value: val, isSet: true}
}

func (v NullableAdditionalConstraintAtLeastOneValidCapacity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdditionalConstraintAtLeastOneValidCapacity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


