/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FromPrevious type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FromPrevious{}

// FromPrevious The travel distance and duration from the previous waypoint to the current one.
type FromPrevious struct {
	TravelDistanceInKm float32 `json:"travelDistanceInKm"`
	// A period of time, expressed in the ISO8601 **duration** format.
	TravelDuration string `json:"travelDuration" validate:"regexp=^P(\\\\d+Y)?(\\\\d+M)?(\\\\d+W)?(\\\\d+D)?(T(\\\\d+H)?(\\\\d+M)?(\\\\d+S)?)?$"`
}

type _FromPrevious FromPrevious

// NewFromPrevious instantiates a new FromPrevious object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFromPrevious(travelDistanceInKm float32, travelDuration string) *FromPrevious {
	this := FromPrevious{}
	this.TravelDistanceInKm = travelDistanceInKm
	this.TravelDuration = travelDuration
	return &this
}

// NewFromPreviousWithDefaults instantiates a new FromPrevious object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFromPreviousWithDefaults() *FromPrevious {
	this := FromPrevious{}
	return &this
}

// GetTravelDistanceInKm returns the TravelDistanceInKm field value
func (o *FromPrevious) GetTravelDistanceInKm() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TravelDistanceInKm
}

// GetTravelDistanceInKmOk returns a tuple with the TravelDistanceInKm field value
// and a boolean to check if the value has been set.
func (o *FromPrevious) GetTravelDistanceInKmOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TravelDistanceInKm, true
}

// SetTravelDistanceInKm sets field value
func (o *FromPrevious) SetTravelDistanceInKm(v float32) {
	o.TravelDistanceInKm = v
}

// GetTravelDuration returns the TravelDuration field value
func (o *FromPrevious) GetTravelDuration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TravelDuration
}

// GetTravelDurationOk returns a tuple with the TravelDuration field value
// and a boolean to check if the value has been set.
func (o *FromPrevious) GetTravelDurationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TravelDuration, true
}

// SetTravelDuration sets field value
func (o *FromPrevious) SetTravelDuration(v string) {
	o.TravelDuration = v
}

func (o FromPrevious) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FromPrevious) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["travelDistanceInKm"] = o.TravelDistanceInKm
	toSerialize["travelDuration"] = o.TravelDuration
	return toSerialize, nil
}

func (o *FromPrevious) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"travelDistanceInKm",
		"travelDuration",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFromPrevious := _FromPrevious{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFromPrevious)

	if err != nil {
		return err
	}

	*o = FromPrevious(varFromPrevious)

	return err
}

type NullableFromPrevious struct {
	value *FromPrevious
	isSet bool
}

func (v NullableFromPrevious) Get() *FromPrevious {
	return v.value
}

func (v *NullableFromPrevious) Set(val *FromPrevious) {
	v.value = val
	v.isSet = true
}

func (v NullableFromPrevious) IsSet() bool {
	return v.isSet
}

func (v *NullableFromPrevious) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFromPrevious(val *FromPrevious) *NullableFromPrevious {
	return &NullableFromPrevious{value: val, isSet: true}
}

func (v NullableFromPrevious) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFromPrevious) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


