/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OperationDurationPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperationDurationPolicy{}

// OperationDurationPolicy Policy to indicate which operation duration must not be taken into account.
type OperationDurationPolicy struct {
	Policy string `json:"policy"`
	StopTags []string `json:"stopTags,omitempty"`
}

type _OperationDurationPolicy OperationDurationPolicy

// NewOperationDurationPolicy instantiates a new OperationDurationPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationDurationPolicy(policy string) *OperationDurationPolicy {
	this := OperationDurationPolicy{}
	this.Policy = policy
	return &this
}

// NewOperationDurationPolicyWithDefaults instantiates a new OperationDurationPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationDurationPolicyWithDefaults() *OperationDurationPolicy {
	this := OperationDurationPolicy{}
	return &this
}

// GetPolicy returns the Policy field value
func (o *OperationDurationPolicy) GetPolicy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value
// and a boolean to check if the value has been set.
func (o *OperationDurationPolicy) GetPolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Policy, true
}

// SetPolicy sets field value
func (o *OperationDurationPolicy) SetPolicy(v string) {
	o.Policy = v
}

// GetStopTags returns the StopTags field value if set, zero value otherwise.
func (o *OperationDurationPolicy) GetStopTags() []string {
	if o == nil || IsNil(o.StopTags) {
		var ret []string
		return ret
	}
	return o.StopTags
}

// GetStopTagsOk returns a tuple with the StopTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperationDurationPolicy) GetStopTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.StopTags) {
		return nil, false
	}
	return o.StopTags, true
}

// HasStopTags returns a boolean if a field has been set.
func (o *OperationDurationPolicy) HasStopTags() bool {
	if o != nil && !IsNil(o.StopTags) {
		return true
	}

	return false
}

// SetStopTags gets a reference to the given []string and assigns it to the StopTags field.
func (o *OperationDurationPolicy) SetStopTags(v []string) {
	o.StopTags = v
}

func (o OperationDurationPolicy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperationDurationPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["policy"] = o.Policy
	if !IsNil(o.StopTags) {
		toSerialize["stopTags"] = o.StopTags
	}
	return toSerialize, nil
}

func (o *OperationDurationPolicy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"policy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperationDurationPolicy := _OperationDurationPolicy{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperationDurationPolicy)

	if err != nil {
		return err
	}

	*o = OperationDurationPolicy(varOperationDurationPolicy)

	return err
}

type NullableOperationDurationPolicy struct {
	value *OperationDurationPolicy
	isSet bool
}

func (v NullableOperationDurationPolicy) Get() *OperationDurationPolicy {
	return v.value
}

func (v *NullableOperationDurationPolicy) Set(val *OperationDurationPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationDurationPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationDurationPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationDurationPolicy(val *OperationDurationPolicy) *NullableOperationDurationPolicy {
	return &NullableOperationDurationPolicy{value: val, isSet: true}
}

func (v NullableOperationDurationPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationDurationPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


