/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EnvelopedPlanStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvelopedPlanStatus{}

// EnvelopedPlanStatus struct for EnvelopedPlanStatus
type EnvelopedPlanStatus struct {
	Item *PlanStatus `json:"item,omitempty"`
	AgencyId *interface{} `json:"agencyId,omitempty"`
	PlanId *interface{} `json:"planId,omitempty"`
	// The plan version.
	PlanVersion *int32 `json:"planVersion,omitempty"`
}

// NewEnvelopedPlanStatus instantiates a new EnvelopedPlanStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvelopedPlanStatus() *EnvelopedPlanStatus {
	this := EnvelopedPlanStatus{}
	return &this
}

// NewEnvelopedPlanStatusWithDefaults instantiates a new EnvelopedPlanStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvelopedPlanStatusWithDefaults() *EnvelopedPlanStatus {
	this := EnvelopedPlanStatus{}
	return &this
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *EnvelopedPlanStatus) GetItem() PlanStatus {
	if o == nil || IsNil(o.Item) {
		var ret PlanStatus
		return ret
	}
	return *o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvelopedPlanStatus) GetItemOk() (*PlanStatus, bool) {
	if o == nil || IsNil(o.Item) {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *EnvelopedPlanStatus) HasItem() bool {
	if o != nil && !IsNil(o.Item) {
		return true
	}

	return false
}

// SetItem gets a reference to the given PlanStatus and assigns it to the Item field.
func (o *EnvelopedPlanStatus) SetItem(v PlanStatus) {
	o.Item = &v
}

// GetAgencyId returns the AgencyId field value if set, zero value otherwise.
func (o *EnvelopedPlanStatus) GetAgencyId() interface{} {
	if o == nil || IsNil(o.AgencyId) {
		var ret interface{}
		return ret
	}
	return *o.AgencyId
}

// GetAgencyIdOk returns a tuple with the AgencyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvelopedPlanStatus) GetAgencyIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.AgencyId) {
		return nil, false
	}
	return o.AgencyId, true
}

// HasAgencyId returns a boolean if a field has been set.
func (o *EnvelopedPlanStatus) HasAgencyId() bool {
	if o != nil && !IsNil(o.AgencyId) {
		return true
	}

	return false
}

// SetAgencyId gets a reference to the given interface{} and assigns it to the AgencyId field.
func (o *EnvelopedPlanStatus) SetAgencyId(v interface{}) {
	o.AgencyId = &v
}

// GetPlanId returns the PlanId field value if set, zero value otherwise.
func (o *EnvelopedPlanStatus) GetPlanId() interface{} {
	if o == nil || IsNil(o.PlanId) {
		var ret interface{}
		return ret
	}
	return *o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvelopedPlanStatus) GetPlanIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.PlanId) {
		return nil, false
	}
	return o.PlanId, true
}

// HasPlanId returns a boolean if a field has been set.
func (o *EnvelopedPlanStatus) HasPlanId() bool {
	if o != nil && !IsNil(o.PlanId) {
		return true
	}

	return false
}

// SetPlanId gets a reference to the given interface{} and assigns it to the PlanId field.
func (o *EnvelopedPlanStatus) SetPlanId(v interface{}) {
	o.PlanId = &v
}

// GetPlanVersion returns the PlanVersion field value if set, zero value otherwise.
func (o *EnvelopedPlanStatus) GetPlanVersion() int32 {
	if o == nil || IsNil(o.PlanVersion) {
		var ret int32
		return ret
	}
	return *o.PlanVersion
}

// GetPlanVersionOk returns a tuple with the PlanVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvelopedPlanStatus) GetPlanVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.PlanVersion) {
		return nil, false
	}
	return o.PlanVersion, true
}

// HasPlanVersion returns a boolean if a field has been set.
func (o *EnvelopedPlanStatus) HasPlanVersion() bool {
	if o != nil && !IsNil(o.PlanVersion) {
		return true
	}

	return false
}

// SetPlanVersion gets a reference to the given int32 and assigns it to the PlanVersion field.
func (o *EnvelopedPlanStatus) SetPlanVersion(v int32) {
	o.PlanVersion = &v
}

func (o EnvelopedPlanStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvelopedPlanStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Item) {
		toSerialize["item"] = o.Item
	}
	if !IsNil(o.AgencyId) {
		toSerialize["agencyId"] = o.AgencyId
	}
	if !IsNil(o.PlanId) {
		toSerialize["planId"] = o.PlanId
	}
	if !IsNil(o.PlanVersion) {
		toSerialize["planVersion"] = o.PlanVersion
	}
	return toSerialize, nil
}

type NullableEnvelopedPlanStatus struct {
	value *EnvelopedPlanStatus
	isSet bool
}

func (v NullableEnvelopedPlanStatus) Get() *EnvelopedPlanStatus {
	return v.value
}

func (v *NullableEnvelopedPlanStatus) Set(val *EnvelopedPlanStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvelopedPlanStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvelopedPlanStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvelopedPlanStatus(val *EnvelopedPlanStatus) *NullableEnvelopedPlanStatus {
	return &NullableEnvelopedPlanStatus{value: val, isSet: true}
}

func (v NullableEnvelopedPlanStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvelopedPlanStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


