/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ClientForCreation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientForCreation{}

// ClientForCreation A Kardinal's client payload for creation.
type ClientForCreation struct {
	Id interface{} `json:"id"`
	// The client name.
	Name *string `json:"name,omitempty"`
	Prefix interface{} `json:"prefix"`
	Conf NullableClientConf `json:"conf,omitempty"`
}

type _ClientForCreation ClientForCreation

// NewClientForCreation instantiates a new ClientForCreation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientForCreation(id interface{}, prefix interface{}) *ClientForCreation {
	this := ClientForCreation{}
	this.Id = id
	this.Prefix = prefix
	return &this
}

// NewClientForCreationWithDefaults instantiates a new ClientForCreation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientForCreationWithDefaults() *ClientForCreation {
	this := ClientForCreation{}
	return &this
}

// GetId returns the Id field value
func (o *ClientForCreation) GetId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ClientForCreation) GetIdOk() (*interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ClientForCreation) SetId(v interface{}) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ClientForCreation) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientForCreation) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ClientForCreation) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ClientForCreation) SetName(v string) {
	o.Name = &v
}

// GetPrefix returns the Prefix field value
func (o *ClientForCreation) GetPrefix() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value
// and a boolean to check if the value has been set.
func (o *ClientForCreation) GetPrefixOk() (*interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prefix, true
}

// SetPrefix sets field value
func (o *ClientForCreation) SetPrefix(v interface{}) {
	o.Prefix = v
}

// GetConf returns the Conf field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ClientForCreation) GetConf() ClientConf {
	if o == nil || IsNil(o.Conf.Get()) {
		var ret ClientConf
		return ret
	}
	return *o.Conf.Get()
}

// GetConfOk returns a tuple with the Conf field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ClientForCreation) GetConfOk() (*ClientConf, bool) {
	if o == nil {
		return nil, false
	}
	return o.Conf.Get(), o.Conf.IsSet()
}

// HasConf returns a boolean if a field has been set.
func (o *ClientForCreation) HasConf() bool {
	if o != nil && o.Conf.IsSet() {
		return true
	}

	return false
}

// SetConf gets a reference to the given NullableClientConf and assigns it to the Conf field.
func (o *ClientForCreation) SetConf(v ClientConf) {
	o.Conf.Set(&v)
}
// SetConfNil sets the value for Conf to be an explicit nil
func (o *ClientForCreation) SetConfNil() {
	o.Conf.Set(nil)
}

// UnsetConf ensures that no value is present for Conf, not even an explicit nil
func (o *ClientForCreation) UnsetConf() {
	o.Conf.Unset()
}

func (o ClientForCreation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientForCreation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["prefix"] = o.Prefix
	if o.Conf.IsSet() {
		toSerialize["conf"] = o.Conf.Get()
	}
	return toSerialize, nil
}

func (o *ClientForCreation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"prefix",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClientForCreation := _ClientForCreation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClientForCreation)

	if err != nil {
		return err
	}

	*o = ClientForCreation(varClientForCreation)

	return err
}

type NullableClientForCreation struct {
	value *ClientForCreation
	isSet bool
}

func (v NullableClientForCreation) Get() *ClientForCreation {
	return v.value
}

func (v *NullableClientForCreation) Set(val *ClientForCreation) {
	v.value = val
	v.isSet = true
}

func (v NullableClientForCreation) IsSet() bool {
	return v.isSet
}

func (v *NullableClientForCreation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientForCreation(val *ClientForCreation) *NullableClientForCreation {
	return &NullableClientForCreation{value: val, isSet: true}
}

func (v NullableClientForCreation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientForCreation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


