/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VehicleProfileBicycle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VehicleProfileBicycle{}

// VehicleProfileBicycle struct for VehicleProfileBicycle
type VehicleProfileBicycle struct {
	Type string `json:"type"`
	ExcludedCountries []string `json:"excludedCountries,omitempty"`
}

type _VehicleProfileBicycle VehicleProfileBicycle

// NewVehicleProfileBicycle instantiates a new VehicleProfileBicycle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVehicleProfileBicycle(type_ string) *VehicleProfileBicycle {
	this := VehicleProfileBicycle{}
	this.Type = type_
	return &this
}

// NewVehicleProfileBicycleWithDefaults instantiates a new VehicleProfileBicycle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVehicleProfileBicycleWithDefaults() *VehicleProfileBicycle {
	this := VehicleProfileBicycle{}
	return &this
}

// GetType returns the Type field value
func (o *VehicleProfileBicycle) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *VehicleProfileBicycle) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *VehicleProfileBicycle) SetType(v string) {
	o.Type = v
}

// GetExcludedCountries returns the ExcludedCountries field value if set, zero value otherwise.
func (o *VehicleProfileBicycle) GetExcludedCountries() []string {
	if o == nil || IsNil(o.ExcludedCountries) {
		var ret []string
		return ret
	}
	return o.ExcludedCountries
}

// GetExcludedCountriesOk returns a tuple with the ExcludedCountries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VehicleProfileBicycle) GetExcludedCountriesOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludedCountries) {
		return nil, false
	}
	return o.ExcludedCountries, true
}

// HasExcludedCountries returns a boolean if a field has been set.
func (o *VehicleProfileBicycle) HasExcludedCountries() bool {
	if o != nil && !IsNil(o.ExcludedCountries) {
		return true
	}

	return false
}

// SetExcludedCountries gets a reference to the given []string and assigns it to the ExcludedCountries field.
func (o *VehicleProfileBicycle) SetExcludedCountries(v []string) {
	o.ExcludedCountries = v
}

func (o VehicleProfileBicycle) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VehicleProfileBicycle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.ExcludedCountries) {
		toSerialize["excludedCountries"] = o.ExcludedCountries
	}
	return toSerialize, nil
}

func (o *VehicleProfileBicycle) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVehicleProfileBicycle := _VehicleProfileBicycle{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVehicleProfileBicycle)

	if err != nil {
		return err
	}

	*o = VehicleProfileBicycle(varVehicleProfileBicycle)

	return err
}

type NullableVehicleProfileBicycle struct {
	value *VehicleProfileBicycle
	isSet bool
}

func (v NullableVehicleProfileBicycle) Get() *VehicleProfileBicycle {
	return v.value
}

func (v *NullableVehicleProfileBicycle) Set(val *VehicleProfileBicycle) {
	v.value = val
	v.isSet = true
}

func (v NullableVehicleProfileBicycle) IsSet() bool {
	return v.isSet
}

func (v *NullableVehicleProfileBicycle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVehicleProfileBicycle(val *VehicleProfileBicycle) *NullableVehicleProfileBicycle {
	return &NullableVehicleProfileBicycle{value: val, isSet: true}
}

func (v NullableVehicleProfileBicycle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVehicleProfileBicycle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


