/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebhookUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookUpdate{}

// WebhookUpdate struct for WebhookUpdate
type WebhookUpdate struct {
	// The secure webhook URL (must be https).
	Url string `json:"url"`
	// A map of header key-value pairs.
	Headers *map[string]string `json:"headers,omitempty"`
	// Specifies whether we should also provide the plan in the webhook's payload.
	WithPlan *bool `json:"withPlan,omitempty"`
	// Specifies whether the webhook is active or not.
	Active *bool `json:"active,omitempty"`
}

type _WebhookUpdate WebhookUpdate

// NewWebhookUpdate instantiates a new WebhookUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookUpdate(url string) *WebhookUpdate {
	this := WebhookUpdate{}
	this.Url = url
	var withPlan bool = false
	this.WithPlan = &withPlan
	var active bool = true
	this.Active = &active
	return &this
}

// NewWebhookUpdateWithDefaults instantiates a new WebhookUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookUpdateWithDefaults() *WebhookUpdate {
	this := WebhookUpdate{}
	var withPlan bool = false
	this.WithPlan = &withPlan
	var active bool = true
	this.Active = &active
	return &this
}

// GetUrl returns the Url field value
func (o *WebhookUpdate) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhookUpdate) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhookUpdate) SetUrl(v string) {
	o.Url = v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *WebhookUpdate) GetHeaders() map[string]string {
	if o == nil || IsNil(o.Headers) {
		var ret map[string]string
		return ret
	}
	return *o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookUpdate) GetHeadersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *WebhookUpdate) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]string and assigns it to the Headers field.
func (o *WebhookUpdate) SetHeaders(v map[string]string) {
	o.Headers = &v
}

// GetWithPlan returns the WithPlan field value if set, zero value otherwise.
func (o *WebhookUpdate) GetWithPlan() bool {
	if o == nil || IsNil(o.WithPlan) {
		var ret bool
		return ret
	}
	return *o.WithPlan
}

// GetWithPlanOk returns a tuple with the WithPlan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookUpdate) GetWithPlanOk() (*bool, bool) {
	if o == nil || IsNil(o.WithPlan) {
		return nil, false
	}
	return o.WithPlan, true
}

// HasWithPlan returns a boolean if a field has been set.
func (o *WebhookUpdate) HasWithPlan() bool {
	if o != nil && !IsNil(o.WithPlan) {
		return true
	}

	return false
}

// SetWithPlan gets a reference to the given bool and assigns it to the WithPlan field.
func (o *WebhookUpdate) SetWithPlan(v bool) {
	o.WithPlan = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *WebhookUpdate) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookUpdate) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *WebhookUpdate) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *WebhookUpdate) SetActive(v bool) {
	o.Active = &v
}

func (o WebhookUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.WithPlan) {
		toSerialize["withPlan"] = o.WithPlan
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	return toSerialize, nil
}

func (o *WebhookUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookUpdate := _WebhookUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookUpdate)

	if err != nil {
		return err
	}

	*o = WebhookUpdate(varWebhookUpdate)

	return err
}

type NullableWebhookUpdate struct {
	value *WebhookUpdate
	isSet bool
}

func (v NullableWebhookUpdate) Get() *WebhookUpdate {
	return v.value
}

func (v *NullableWebhookUpdate) Set(val *WebhookUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookUpdate(val *WebhookUpdate) *NullableWebhookUpdate {
	return &NullableWebhookUpdate{value: val, isSet: true}
}

func (v NullableWebhookUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


