/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TAOConfSpecific type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TAOConfSpecific{}

// TAOConfSpecific A product complementary configuration for TAO.
type TAOConfSpecific struct {
	RequiredProperties *TAOConfRequiredProperties `json:"requiredProperties,omitempty"`
	MaxSectorizationsInParallel *float32 `json:"maxSectorizationsInParallel,omitempty"`
}

// NewTAOConfSpecific instantiates a new TAOConfSpecific object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTAOConfSpecific() *TAOConfSpecific {
	this := TAOConfSpecific{}
	var maxSectorizationsInParallel float32 = 5
	this.MaxSectorizationsInParallel = &maxSectorizationsInParallel
	return &this
}

// NewTAOConfSpecificWithDefaults instantiates a new TAOConfSpecific object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTAOConfSpecificWithDefaults() *TAOConfSpecific {
	this := TAOConfSpecific{}
	var maxSectorizationsInParallel float32 = 5
	this.MaxSectorizationsInParallel = &maxSectorizationsInParallel
	return &this
}

// GetRequiredProperties returns the RequiredProperties field value if set, zero value otherwise.
func (o *TAOConfSpecific) GetRequiredProperties() TAOConfRequiredProperties {
	if o == nil || IsNil(o.RequiredProperties) {
		var ret TAOConfRequiredProperties
		return ret
	}
	return *o.RequiredProperties
}

// GetRequiredPropertiesOk returns a tuple with the RequiredProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TAOConfSpecific) GetRequiredPropertiesOk() (*TAOConfRequiredProperties, bool) {
	if o == nil || IsNil(o.RequiredProperties) {
		return nil, false
	}
	return o.RequiredProperties, true
}

// HasRequiredProperties returns a boolean if a field has been set.
func (o *TAOConfSpecific) HasRequiredProperties() bool {
	if o != nil && !IsNil(o.RequiredProperties) {
		return true
	}

	return false
}

// SetRequiredProperties gets a reference to the given TAOConfRequiredProperties and assigns it to the RequiredProperties field.
func (o *TAOConfSpecific) SetRequiredProperties(v TAOConfRequiredProperties) {
	o.RequiredProperties = &v
}

// GetMaxSectorizationsInParallel returns the MaxSectorizationsInParallel field value if set, zero value otherwise.
func (o *TAOConfSpecific) GetMaxSectorizationsInParallel() float32 {
	if o == nil || IsNil(o.MaxSectorizationsInParallel) {
		var ret float32
		return ret
	}
	return *o.MaxSectorizationsInParallel
}

// GetMaxSectorizationsInParallelOk returns a tuple with the MaxSectorizationsInParallel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TAOConfSpecific) GetMaxSectorizationsInParallelOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxSectorizationsInParallel) {
		return nil, false
	}
	return o.MaxSectorizationsInParallel, true
}

// HasMaxSectorizationsInParallel returns a boolean if a field has been set.
func (o *TAOConfSpecific) HasMaxSectorizationsInParallel() bool {
	if o != nil && !IsNil(o.MaxSectorizationsInParallel) {
		return true
	}

	return false
}

// SetMaxSectorizationsInParallel gets a reference to the given float32 and assigns it to the MaxSectorizationsInParallel field.
func (o *TAOConfSpecific) SetMaxSectorizationsInParallel(v float32) {
	o.MaxSectorizationsInParallel = &v
}

func (o TAOConfSpecific) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TAOConfSpecific) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RequiredProperties) {
		toSerialize["requiredProperties"] = o.RequiredProperties
	}
	if !IsNil(o.MaxSectorizationsInParallel) {
		toSerialize["maxSectorizationsInParallel"] = o.MaxSectorizationsInParallel
	}
	return toSerialize, nil
}

type NullableTAOConfSpecific struct {
	value *TAOConfSpecific
	isSet bool
}

func (v NullableTAOConfSpecific) Get() *TAOConfSpecific {
	return v.value
}

func (v *NullableTAOConfSpecific) Set(val *TAOConfSpecific) {
	v.value = val
	v.isSet = true
}

func (v NullableTAOConfSpecific) IsSet() bool {
	return v.isSet
}

func (v *NullableTAOConfSpecific) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTAOConfSpecific(val *TAOConfSpecific) *NullableTAOConfSpecific {
	return &NullableTAOConfSpecific{value: val, isSet: true}
}

func (v NullableTAOConfSpecific) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTAOConfSpecific) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


