/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// RequestMFAConfigUpdate200Response - struct for RequestMFAConfigUpdate200Response
type RequestMFAConfigUpdate200Response struct {
	EnvelopedMFARequestOTPOutput *EnvelopedMFARequestOTPOutput
	EnvelopedMFARequestTOTPOutput *EnvelopedMFARequestTOTPOutput
}

// EnvelopedMFARequestOTPOutputAsRequestMFAConfigUpdate200Response is a convenience function that returns EnvelopedMFARequestOTPOutput wrapped in RequestMFAConfigUpdate200Response
func EnvelopedMFARequestOTPOutputAsRequestMFAConfigUpdate200Response(v *EnvelopedMFARequestOTPOutput) RequestMFAConfigUpdate200Response {
	return RequestMFAConfigUpdate200Response{
		EnvelopedMFARequestOTPOutput: v,
	}
}

// EnvelopedMFARequestTOTPOutputAsRequestMFAConfigUpdate200Response is a convenience function that returns EnvelopedMFARequestTOTPOutput wrapped in RequestMFAConfigUpdate200Response
func EnvelopedMFARequestTOTPOutputAsRequestMFAConfigUpdate200Response(v *EnvelopedMFARequestTOTPOutput) RequestMFAConfigUpdate200Response {
	return RequestMFAConfigUpdate200Response{
		EnvelopedMFARequestTOTPOutput: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *RequestMFAConfigUpdate200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into EnvelopedMFARequestOTPOutput
	err = newStrictDecoder(data).Decode(&dst.EnvelopedMFARequestOTPOutput)
	if err == nil {
		jsonEnvelopedMFARequestOTPOutput, _ := json.Marshal(dst.EnvelopedMFARequestOTPOutput)
		if string(jsonEnvelopedMFARequestOTPOutput) == "{}" { // empty struct
			dst.EnvelopedMFARequestOTPOutput = nil
		} else {
			if err = validator.Validate(dst.EnvelopedMFARequestOTPOutput); err != nil {
				dst.EnvelopedMFARequestOTPOutput = nil
			} else {
				match++
			}
		}
	} else {
		dst.EnvelopedMFARequestOTPOutput = nil
	}

	// try to unmarshal data into EnvelopedMFARequestTOTPOutput
	err = newStrictDecoder(data).Decode(&dst.EnvelopedMFARequestTOTPOutput)
	if err == nil {
		jsonEnvelopedMFARequestTOTPOutput, _ := json.Marshal(dst.EnvelopedMFARequestTOTPOutput)
		if string(jsonEnvelopedMFARequestTOTPOutput) == "{}" { // empty struct
			dst.EnvelopedMFARequestTOTPOutput = nil
		} else {
			if err = validator.Validate(dst.EnvelopedMFARequestTOTPOutput); err != nil {
				dst.EnvelopedMFARequestTOTPOutput = nil
			} else {
				match++
			}
		}
	} else {
		dst.EnvelopedMFARequestTOTPOutput = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.EnvelopedMFARequestOTPOutput = nil
		dst.EnvelopedMFARequestTOTPOutput = nil

		return fmt.Errorf("data matches more than one schema in oneOf(RequestMFAConfigUpdate200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(RequestMFAConfigUpdate200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RequestMFAConfigUpdate200Response) MarshalJSON() ([]byte, error) {
	if src.EnvelopedMFARequestOTPOutput != nil {
		return json.Marshal(&src.EnvelopedMFARequestOTPOutput)
	}

	if src.EnvelopedMFARequestTOTPOutput != nil {
		return json.Marshal(&src.EnvelopedMFARequestTOTPOutput)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *RequestMFAConfigUpdate200Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.EnvelopedMFARequestOTPOutput != nil {
		return obj.EnvelopedMFARequestOTPOutput
	}

	if obj.EnvelopedMFARequestTOTPOutput != nil {
		return obj.EnvelopedMFARequestTOTPOutput
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj RequestMFAConfigUpdate200Response) GetActualInstanceValue() (interface{}) {
	if obj.EnvelopedMFARequestOTPOutput != nil {
		return *obj.EnvelopedMFARequestOTPOutput
	}

	if obj.EnvelopedMFARequestTOTPOutput != nil {
		return *obj.EnvelopedMFARequestTOTPOutput
	}

	// all schemas are nil
	return nil
}

type NullableRequestMFAConfigUpdate200Response struct {
	value *RequestMFAConfigUpdate200Response
	isSet bool
}

func (v NullableRequestMFAConfigUpdate200Response) Get() *RequestMFAConfigUpdate200Response {
	return v.value
}

func (v *NullableRequestMFAConfigUpdate200Response) Set(val *RequestMFAConfigUpdate200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestMFAConfigUpdate200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestMFAConfigUpdate200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestMFAConfigUpdate200Response(val *RequestMFAConfigUpdate200Response) *NullableRequestMFAConfigUpdate200Response {
	return &NullableRequestMFAConfigUpdate200Response{value: val, isSet: true}
}

func (v NullableRequestMFAConfigUpdate200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestMFAConfigUpdate200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


