/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AssignmentEnd type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssignmentEnd{}

// AssignmentEnd struct for AssignmentEnd
type AssignmentEnd struct {
	Type string `json:"type"`
	Status *AssignmentStatus `json:"status,omitempty"`
	// A full calendar date time, expressed in the ISO8601 **date** format: YYYY-MM-DDThh:mm:ssZ.
	ArrivalTime string `json:"arrivalTime"`
}

type _AssignmentEnd AssignmentEnd

// NewAssignmentEnd instantiates a new AssignmentEnd object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssignmentEnd(type_ string, arrivalTime string) *AssignmentEnd {
	this := AssignmentEnd{}
	this.Type = type_
	var status AssignmentStatus = ASSIGNMENTSTATUS_FIXED
	this.Status = &status
	this.ArrivalTime = arrivalTime
	return &this
}

// NewAssignmentEndWithDefaults instantiates a new AssignmentEnd object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssignmentEndWithDefaults() *AssignmentEnd {
	this := AssignmentEnd{}
	var status AssignmentStatus = ASSIGNMENTSTATUS_FIXED
	this.Status = &status
	return &this
}

// GetType returns the Type field value
func (o *AssignmentEnd) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AssignmentEnd) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AssignmentEnd) SetType(v string) {
	o.Type = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AssignmentEnd) GetStatus() AssignmentStatus {
	if o == nil || IsNil(o.Status) {
		var ret AssignmentStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentEnd) GetStatusOk() (*AssignmentStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AssignmentEnd) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given AssignmentStatus and assigns it to the Status field.
func (o *AssignmentEnd) SetStatus(v AssignmentStatus) {
	o.Status = &v
}

// GetArrivalTime returns the ArrivalTime field value
func (o *AssignmentEnd) GetArrivalTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ArrivalTime
}

// GetArrivalTimeOk returns a tuple with the ArrivalTime field value
// and a boolean to check if the value has been set.
func (o *AssignmentEnd) GetArrivalTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArrivalTime, true
}

// SetArrivalTime sets field value
func (o *AssignmentEnd) SetArrivalTime(v string) {
	o.ArrivalTime = v
}

func (o AssignmentEnd) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssignmentEnd) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	toSerialize["arrivalTime"] = o.ArrivalTime
	return toSerialize, nil
}

func (o *AssignmentEnd) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"arrivalTime",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssignmentEnd := _AssignmentEnd{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssignmentEnd)

	if err != nil {
		return err
	}

	*o = AssignmentEnd(varAssignmentEnd)

	return err
}

type NullableAssignmentEnd struct {
	value *AssignmentEnd
	isSet bool
}

func (v NullableAssignmentEnd) Get() *AssignmentEnd {
	return v.value
}

func (v *NullableAssignmentEnd) Set(val *AssignmentEnd) {
	v.value = val
	v.isSet = true
}

func (v NullableAssignmentEnd) IsSet() bool {
	return v.isSet
}

func (v *NullableAssignmentEnd) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssignmentEnd(val *AssignmentEnd) *NullableAssignmentEnd {
	return &NullableAssignmentEnd{value: val, isSet: true}
}

func (v NullableAssignmentEnd) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssignmentEnd) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


