/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EnvelopedMFARequestOTPOutputItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvelopedMFARequestOTPOutputItem{}

// EnvelopedMFARequestOTPOutputItem struct for EnvelopedMFARequestOTPOutputItem
type EnvelopedMFARequestOTPOutputItem struct {
	// A JSON Web Token with scope 'otp', to be used with an OTP (One-Time Password) value, valid for 10 minutes.
	OtpToken *string `json:"otpToken,omitempty"`
}

// NewEnvelopedMFARequestOTPOutputItem instantiates a new EnvelopedMFARequestOTPOutputItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvelopedMFARequestOTPOutputItem() *EnvelopedMFARequestOTPOutputItem {
	this := EnvelopedMFARequestOTPOutputItem{}
	return &this
}

// NewEnvelopedMFARequestOTPOutputItemWithDefaults instantiates a new EnvelopedMFARequestOTPOutputItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvelopedMFARequestOTPOutputItemWithDefaults() *EnvelopedMFARequestOTPOutputItem {
	this := EnvelopedMFARequestOTPOutputItem{}
	return &this
}

// GetOtpToken returns the OtpToken field value if set, zero value otherwise.
func (o *EnvelopedMFARequestOTPOutputItem) GetOtpToken() string {
	if o == nil || IsNil(o.OtpToken) {
		var ret string
		return ret
	}
	return *o.OtpToken
}

// GetOtpTokenOk returns a tuple with the OtpToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvelopedMFARequestOTPOutputItem) GetOtpTokenOk() (*string, bool) {
	if o == nil || IsNil(o.OtpToken) {
		return nil, false
	}
	return o.OtpToken, true
}

// HasOtpToken returns a boolean if a field has been set.
func (o *EnvelopedMFARequestOTPOutputItem) HasOtpToken() bool {
	if o != nil && !IsNil(o.OtpToken) {
		return true
	}

	return false
}

// SetOtpToken gets a reference to the given string and assigns it to the OtpToken field.
func (o *EnvelopedMFARequestOTPOutputItem) SetOtpToken(v string) {
	o.OtpToken = &v
}

func (o EnvelopedMFARequestOTPOutputItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvelopedMFARequestOTPOutputItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OtpToken) {
		toSerialize["otpToken"] = o.OtpToken
	}
	return toSerialize, nil
}

type NullableEnvelopedMFARequestOTPOutputItem struct {
	value *EnvelopedMFARequestOTPOutputItem
	isSet bool
}

func (v NullableEnvelopedMFARequestOTPOutputItem) Get() *EnvelopedMFARequestOTPOutputItem {
	return v.value
}

func (v *NullableEnvelopedMFARequestOTPOutputItem) Set(val *EnvelopedMFARequestOTPOutputItem) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvelopedMFARequestOTPOutputItem) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvelopedMFARequestOTPOutputItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvelopedMFARequestOTPOutputItem(val *EnvelopedMFARequestOTPOutputItem) *NullableEnvelopedMFARequestOTPOutputItem {
	return &NullableEnvelopedMFARequestOTPOutputItem{value: val, isSet: true}
}

func (v NullableEnvelopedMFARequestOTPOutputItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvelopedMFARequestOTPOutputItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


