/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EnvelopedLoginGDPROutputItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvelopedLoginGDPROutputItem{}

// EnvelopedLoginGDPROutputItem struct for EnvelopedLoginGDPROutputItem
type EnvelopedLoginGDPROutputItem struct {
	// A JSON Web Token with scope 'gdpr', to be used to approve a GDPR policy, valid for 1 hour.
	GdprToken *string `json:"gdprToken,omitempty"`
}

// NewEnvelopedLoginGDPROutputItem instantiates a new EnvelopedLoginGDPROutputItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvelopedLoginGDPROutputItem() *EnvelopedLoginGDPROutputItem {
	this := EnvelopedLoginGDPROutputItem{}
	return &this
}

// NewEnvelopedLoginGDPROutputItemWithDefaults instantiates a new EnvelopedLoginGDPROutputItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvelopedLoginGDPROutputItemWithDefaults() *EnvelopedLoginGDPROutputItem {
	this := EnvelopedLoginGDPROutputItem{}
	return &this
}

// GetGdprToken returns the GdprToken field value if set, zero value otherwise.
func (o *EnvelopedLoginGDPROutputItem) GetGdprToken() string {
	if o == nil || IsNil(o.GdprToken) {
		var ret string
		return ret
	}
	return *o.GdprToken
}

// GetGdprTokenOk returns a tuple with the GdprToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvelopedLoginGDPROutputItem) GetGdprTokenOk() (*string, bool) {
	if o == nil || IsNil(o.GdprToken) {
		return nil, false
	}
	return o.GdprToken, true
}

// HasGdprToken returns a boolean if a field has been set.
func (o *EnvelopedLoginGDPROutputItem) HasGdprToken() bool {
	if o != nil && !IsNil(o.GdprToken) {
		return true
	}

	return false
}

// SetGdprToken gets a reference to the given string and assigns it to the GdprToken field.
func (o *EnvelopedLoginGDPROutputItem) SetGdprToken(v string) {
	o.GdprToken = &v
}

func (o EnvelopedLoginGDPROutputItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvelopedLoginGDPROutputItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GdprToken) {
		toSerialize["gdprToken"] = o.GdprToken
	}
	return toSerialize, nil
}

type NullableEnvelopedLoginGDPROutputItem struct {
	value *EnvelopedLoginGDPROutputItem
	isSet bool
}

func (v NullableEnvelopedLoginGDPROutputItem) Get() *EnvelopedLoginGDPROutputItem {
	return v.value
}

func (v *NullableEnvelopedLoginGDPROutputItem) Set(val *EnvelopedLoginGDPROutputItem) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvelopedLoginGDPROutputItem) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvelopedLoginGDPROutputItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvelopedLoginGDPROutputItem(val *EnvelopedLoginGDPROutputItem) *NullableEnvelopedLoginGDPROutputItem {
	return &NullableEnvelopedLoginGDPROutputItem{value: val, isSet: true}
}

func (v NullableEnvelopedLoginGDPROutputItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvelopedLoginGDPROutputItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


