/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EnvelopedAgencies type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvelopedAgencies{}

// EnvelopedAgencies struct for EnvelopedAgencies
type EnvelopedAgencies struct {
	Items []Agency `json:"items,omitempty"`
}

// NewEnvelopedAgencies instantiates a new EnvelopedAgencies object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvelopedAgencies() *EnvelopedAgencies {
	this := EnvelopedAgencies{}
	return &this
}

// NewEnvelopedAgenciesWithDefaults instantiates a new EnvelopedAgencies object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvelopedAgenciesWithDefaults() *EnvelopedAgencies {
	this := EnvelopedAgencies{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *EnvelopedAgencies) GetItems() []Agency {
	if o == nil || IsNil(o.Items) {
		var ret []Agency
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvelopedAgencies) GetItemsOk() ([]Agency, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *EnvelopedAgencies) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Agency and assigns it to the Items field.
func (o *EnvelopedAgencies) SetItems(v []Agency) {
	o.Items = v
}

func (o EnvelopedAgencies) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvelopedAgencies) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableEnvelopedAgencies struct {
	value *EnvelopedAgencies
	isSet bool
}

func (v NullableEnvelopedAgencies) Get() *EnvelopedAgencies {
	return v.value
}

func (v *NullableEnvelopedAgencies) Set(val *EnvelopedAgencies) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvelopedAgencies) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvelopedAgencies) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvelopedAgencies(val *EnvelopedAgencies) *NullableEnvelopedAgencies {
	return &NullableEnvelopedAgencies{value: val, isSet: true}
}

func (v NullableEnvelopedAgencies) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvelopedAgencies) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


