/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MaxWorkingDurationViolation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MaxWorkingDurationViolation{}

// MaxWorkingDurationViolation Violation of a resource's MaxWorkingDuration constraint.
type MaxWorkingDurationViolation struct {
	Type string `json:"type"`
	// The expected maximum working duration.
	MaxWorkingDuration string `json:"maxWorkingDuration" validate:"regexp=^P(\\\\d+Y)?(\\\\d+M)?(\\\\d+W)?(\\\\d+D)?(T(\\\\d+H)?(\\\\d+M)?(\\\\d+S)?)?$"`
	// The duration that exceeds the maximum working duration.
	ExceededDuration string `json:"exceededDuration" validate:"regexp=^P(\\\\d+Y)?(\\\\d+M)?(\\\\d+W)?(\\\\d+D)?(T(\\\\d+H)?(\\\\d+M)?(\\\\d+S)?)?$"`
}

type _MaxWorkingDurationViolation MaxWorkingDurationViolation

// NewMaxWorkingDurationViolation instantiates a new MaxWorkingDurationViolation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMaxWorkingDurationViolation(type_ string, maxWorkingDuration string, exceededDuration string) *MaxWorkingDurationViolation {
	this := MaxWorkingDurationViolation{}
	this.Type = type_
	this.MaxWorkingDuration = maxWorkingDuration
	this.ExceededDuration = exceededDuration
	return &this
}

// NewMaxWorkingDurationViolationWithDefaults instantiates a new MaxWorkingDurationViolation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMaxWorkingDurationViolationWithDefaults() *MaxWorkingDurationViolation {
	this := MaxWorkingDurationViolation{}
	return &this
}

// GetType returns the Type field value
func (o *MaxWorkingDurationViolation) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MaxWorkingDurationViolation) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MaxWorkingDurationViolation) SetType(v string) {
	o.Type = v
}

// GetMaxWorkingDuration returns the MaxWorkingDuration field value
func (o *MaxWorkingDurationViolation) GetMaxWorkingDuration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MaxWorkingDuration
}

// GetMaxWorkingDurationOk returns a tuple with the MaxWorkingDuration field value
// and a boolean to check if the value has been set.
func (o *MaxWorkingDurationViolation) GetMaxWorkingDurationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxWorkingDuration, true
}

// SetMaxWorkingDuration sets field value
func (o *MaxWorkingDurationViolation) SetMaxWorkingDuration(v string) {
	o.MaxWorkingDuration = v
}

// GetExceededDuration returns the ExceededDuration field value
func (o *MaxWorkingDurationViolation) GetExceededDuration() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExceededDuration
}

// GetExceededDurationOk returns a tuple with the ExceededDuration field value
// and a boolean to check if the value has been set.
func (o *MaxWorkingDurationViolation) GetExceededDurationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExceededDuration, true
}

// SetExceededDuration sets field value
func (o *MaxWorkingDurationViolation) SetExceededDuration(v string) {
	o.ExceededDuration = v
}

func (o MaxWorkingDurationViolation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MaxWorkingDurationViolation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["maxWorkingDuration"] = o.MaxWorkingDuration
	toSerialize["exceededDuration"] = o.ExceededDuration
	return toSerialize, nil
}

func (o *MaxWorkingDurationViolation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"maxWorkingDuration",
		"exceededDuration",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMaxWorkingDurationViolation := _MaxWorkingDurationViolation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMaxWorkingDurationViolation)

	if err != nil {
		return err
	}

	*o = MaxWorkingDurationViolation(varMaxWorkingDurationViolation)

	return err
}

type NullableMaxWorkingDurationViolation struct {
	value *MaxWorkingDurationViolation
	isSet bool
}

func (v NullableMaxWorkingDurationViolation) Get() *MaxWorkingDurationViolation {
	return v.value
}

func (v *NullableMaxWorkingDurationViolation) Set(val *MaxWorkingDurationViolation) {
	v.value = val
	v.isSet = true
}

func (v NullableMaxWorkingDurationViolation) IsSet() bool {
	return v.isSet
}

func (v *NullableMaxWorkingDurationViolation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMaxWorkingDurationViolation(val *MaxWorkingDurationViolation) *NullableMaxWorkingDurationViolation {
	return &NullableMaxWorkingDurationViolation{value: val, isSet: true}
}

func (v NullableMaxWorkingDurationViolation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMaxWorkingDurationViolation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


