/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PostLogin200Response - struct for PostLogin200Response
type PostLogin200Response struct {
	EnvelopedLoginAccessOutput *EnvelopedLoginAccessOutput
	EnvelopedLoginGDPROutput *EnvelopedLoginGDPROutput
	EnvelopedLoginMFAOutput *EnvelopedLoginMFAOutput
	EnvelopedLoginOTPOutput *EnvelopedLoginOTPOutput
}

// EnvelopedLoginAccessOutputAsPostLogin200Response is a convenience function that returns EnvelopedLoginAccessOutput wrapped in PostLogin200Response
func EnvelopedLoginAccessOutputAsPostLogin200Response(v *EnvelopedLoginAccessOutput) PostLogin200Response {
	return PostLogin200Response{
		EnvelopedLoginAccessOutput: v,
	}
}

// EnvelopedLoginGDPROutputAsPostLogin200Response is a convenience function that returns EnvelopedLoginGDPROutput wrapped in PostLogin200Response
func EnvelopedLoginGDPROutputAsPostLogin200Response(v *EnvelopedLoginGDPROutput) PostLogin200Response {
	return PostLogin200Response{
		EnvelopedLoginGDPROutput: v,
	}
}

// EnvelopedLoginMFAOutputAsPostLogin200Response is a convenience function that returns EnvelopedLoginMFAOutput wrapped in PostLogin200Response
func EnvelopedLoginMFAOutputAsPostLogin200Response(v *EnvelopedLoginMFAOutput) PostLogin200Response {
	return PostLogin200Response{
		EnvelopedLoginMFAOutput: v,
	}
}

// EnvelopedLoginOTPOutputAsPostLogin200Response is a convenience function that returns EnvelopedLoginOTPOutput wrapped in PostLogin200Response
func EnvelopedLoginOTPOutputAsPostLogin200Response(v *EnvelopedLoginOTPOutput) PostLogin200Response {
	return PostLogin200Response{
		EnvelopedLoginOTPOutput: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PostLogin200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into EnvelopedLoginAccessOutput
	err = newStrictDecoder(data).Decode(&dst.EnvelopedLoginAccessOutput)
	if err == nil {
		jsonEnvelopedLoginAccessOutput, _ := json.Marshal(dst.EnvelopedLoginAccessOutput)
		if string(jsonEnvelopedLoginAccessOutput) == "{}" { // empty struct
			dst.EnvelopedLoginAccessOutput = nil
		} else {
			if err = validator.Validate(dst.EnvelopedLoginAccessOutput); err != nil {
				dst.EnvelopedLoginAccessOutput = nil
			} else {
				match++
			}
		}
	} else {
		dst.EnvelopedLoginAccessOutput = nil
	}

	// try to unmarshal data into EnvelopedLoginGDPROutput
	err = newStrictDecoder(data).Decode(&dst.EnvelopedLoginGDPROutput)
	if err == nil {
		jsonEnvelopedLoginGDPROutput, _ := json.Marshal(dst.EnvelopedLoginGDPROutput)
		if string(jsonEnvelopedLoginGDPROutput) == "{}" { // empty struct
			dst.EnvelopedLoginGDPROutput = nil
		} else {
			if err = validator.Validate(dst.EnvelopedLoginGDPROutput); err != nil {
				dst.EnvelopedLoginGDPROutput = nil
			} else {
				match++
			}
		}
	} else {
		dst.EnvelopedLoginGDPROutput = nil
	}

	// try to unmarshal data into EnvelopedLoginMFAOutput
	err = newStrictDecoder(data).Decode(&dst.EnvelopedLoginMFAOutput)
	if err == nil {
		jsonEnvelopedLoginMFAOutput, _ := json.Marshal(dst.EnvelopedLoginMFAOutput)
		if string(jsonEnvelopedLoginMFAOutput) == "{}" { // empty struct
			dst.EnvelopedLoginMFAOutput = nil
		} else {
			if err = validator.Validate(dst.EnvelopedLoginMFAOutput); err != nil {
				dst.EnvelopedLoginMFAOutput = nil
			} else {
				match++
			}
		}
	} else {
		dst.EnvelopedLoginMFAOutput = nil
	}

	// try to unmarshal data into EnvelopedLoginOTPOutput
	err = newStrictDecoder(data).Decode(&dst.EnvelopedLoginOTPOutput)
	if err == nil {
		jsonEnvelopedLoginOTPOutput, _ := json.Marshal(dst.EnvelopedLoginOTPOutput)
		if string(jsonEnvelopedLoginOTPOutput) == "{}" { // empty struct
			dst.EnvelopedLoginOTPOutput = nil
		} else {
			if err = validator.Validate(dst.EnvelopedLoginOTPOutput); err != nil {
				dst.EnvelopedLoginOTPOutput = nil
			} else {
				match++
			}
		}
	} else {
		dst.EnvelopedLoginOTPOutput = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.EnvelopedLoginAccessOutput = nil
		dst.EnvelopedLoginGDPROutput = nil
		dst.EnvelopedLoginMFAOutput = nil
		dst.EnvelopedLoginOTPOutput = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PostLogin200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PostLogin200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PostLogin200Response) MarshalJSON() ([]byte, error) {
	if src.EnvelopedLoginAccessOutput != nil {
		return json.Marshal(&src.EnvelopedLoginAccessOutput)
	}

	if src.EnvelopedLoginGDPROutput != nil {
		return json.Marshal(&src.EnvelopedLoginGDPROutput)
	}

	if src.EnvelopedLoginMFAOutput != nil {
		return json.Marshal(&src.EnvelopedLoginMFAOutput)
	}

	if src.EnvelopedLoginOTPOutput != nil {
		return json.Marshal(&src.EnvelopedLoginOTPOutput)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PostLogin200Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.EnvelopedLoginAccessOutput != nil {
		return obj.EnvelopedLoginAccessOutput
	}

	if obj.EnvelopedLoginGDPROutput != nil {
		return obj.EnvelopedLoginGDPROutput
	}

	if obj.EnvelopedLoginMFAOutput != nil {
		return obj.EnvelopedLoginMFAOutput
	}

	if obj.EnvelopedLoginOTPOutput != nil {
		return obj.EnvelopedLoginOTPOutput
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PostLogin200Response) GetActualInstanceValue() (interface{}) {
	if obj.EnvelopedLoginAccessOutput != nil {
		return *obj.EnvelopedLoginAccessOutput
	}

	if obj.EnvelopedLoginGDPROutput != nil {
		return *obj.EnvelopedLoginGDPROutput
	}

	if obj.EnvelopedLoginMFAOutput != nil {
		return *obj.EnvelopedLoginMFAOutput
	}

	if obj.EnvelopedLoginOTPOutput != nil {
		return *obj.EnvelopedLoginOTPOutput
	}

	// all schemas are nil
	return nil
}

type NullablePostLogin200Response struct {
	value *PostLogin200Response
	isSet bool
}

func (v NullablePostLogin200Response) Get() *PostLogin200Response {
	return v.value
}

func (v *NullablePostLogin200Response) Set(val *PostLogin200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostLogin200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostLogin200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostLogin200Response(val *PostLogin200Response) *NullablePostLogin200Response {
	return &NullablePostLogin200Response{value: val, isSet: true}
}

func (v NullablePostLogin200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostLogin200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


