/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RegionForUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegionForUpdate{}

// RegionForUpdate A region payload for the update of a region.
type RegionForUpdate struct {
	// The region name.
	Name NullableString `json:"name,omitempty"`
}

// NewRegionForUpdate instantiates a new RegionForUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegionForUpdate() *RegionForUpdate {
	this := RegionForUpdate{}
	return &this
}

// NewRegionForUpdateWithDefaults instantiates a new RegionForUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegionForUpdateWithDefaults() *RegionForUpdate {
	this := RegionForUpdate{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RegionForUpdate) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RegionForUpdate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *RegionForUpdate) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *RegionForUpdate) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *RegionForUpdate) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *RegionForUpdate) UnsetName() {
	o.Name.Unset()
}

func (o RegionForUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegionForUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	return toSerialize, nil
}

type NullableRegionForUpdate struct {
	value *RegionForUpdate
	isSet bool
}

func (v NullableRegionForUpdate) Get() *RegionForUpdate {
	return v.value
}

func (v *NullableRegionForUpdate) Set(val *RegionForUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableRegionForUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableRegionForUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegionForUpdate(val *RegionForUpdate) *NullableRegionForUpdate {
	return &NullableRegionForUpdate{value: val, isSet: true}
}

func (v NullableRegionForUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegionForUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


