/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UserAPIOutputAccessTokens type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserAPIOutputAccessTokens{}

// UserAPIOutputAccessTokens struct for UserAPIOutputAccessTokens
type UserAPIOutputAccessTokens struct {
	// A JSON Web Token with scope 'access', to be used to access protected data, valid for 1 hour.
	AdditionalPropertiesField *string `json:"additionalProperties,omitempty"`
}

// NewUserAPIOutputAccessTokens instantiates a new UserAPIOutputAccessTokens object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserAPIOutputAccessTokens() *UserAPIOutputAccessTokens {
	this := UserAPIOutputAccessTokens{}
	return &this
}

// NewUserAPIOutputAccessTokensWithDefaults instantiates a new UserAPIOutputAccessTokens object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserAPIOutputAccessTokensWithDefaults() *UserAPIOutputAccessTokens {
	this := UserAPIOutputAccessTokens{}
	return &this
}

// GetAdditionalPropertiesField returns the AdditionalPropertiesField field value if set, zero value otherwise.
func (o *UserAPIOutputAccessTokens) GetAdditionalPropertiesField() string {
	if o == nil || IsNil(o.AdditionalPropertiesField) {
		var ret string
		return ret
	}
	return *o.AdditionalPropertiesField
}

// GetAdditionalPropertiesFieldOk returns a tuple with the AdditionalPropertiesField field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAPIOutputAccessTokens) GetAdditionalPropertiesFieldOk() (*string, bool) {
	if o == nil || IsNil(o.AdditionalPropertiesField) {
		return nil, false
	}
	return o.AdditionalPropertiesField, true
}

// HasAdditionalPropertiesField returns a boolean if a field has been set.
func (o *UserAPIOutputAccessTokens) HasAdditionalPropertiesField() bool {
	if o != nil && !IsNil(o.AdditionalPropertiesField) {
		return true
	}

	return false
}

// SetAdditionalPropertiesField gets a reference to the given string and assigns it to the AdditionalPropertiesField field.
func (o *UserAPIOutputAccessTokens) SetAdditionalPropertiesField(v string) {
	o.AdditionalPropertiesField = &v
}

func (o UserAPIOutputAccessTokens) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserAPIOutputAccessTokens) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AdditionalPropertiesField) {
		toSerialize["additionalProperties"] = o.AdditionalPropertiesField
	}
	return toSerialize, nil
}

type NullableUserAPIOutputAccessTokens struct {
	value *UserAPIOutputAccessTokens
	isSet bool
}

func (v NullableUserAPIOutputAccessTokens) Get() *UserAPIOutputAccessTokens {
	return v.value
}

func (v *NullableUserAPIOutputAccessTokens) Set(val *UserAPIOutputAccessTokens) {
	v.value = val
	v.isSet = true
}

func (v NullableUserAPIOutputAccessTokens) IsSet() bool {
	return v.isSet
}

func (v *NullableUserAPIOutputAccessTokens) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserAPIOutputAccessTokens(val *UserAPIOutputAccessTokens) *NullableUserAPIOutputAccessTokens {
	return &NullableUserAPIOutputAccessTokens{value: val, isSet: true}
}

func (v NullableUserAPIOutputAccessTokens) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserAPIOutputAccessTokens) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


