/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PlanObjectivesInner - struct for PlanObjectivesInner
type PlanObjectivesInner struct {
	CustomObjective *CustomObjective
	ObjectivesEnum *ObjectivesEnum
}

// CustomObjectiveAsPlanObjectivesInner is a convenience function that returns CustomObjective wrapped in PlanObjectivesInner
func CustomObjectiveAsPlanObjectivesInner(v *CustomObjective) PlanObjectivesInner {
	return PlanObjectivesInner{
		CustomObjective: v,
	}
}

// ObjectivesEnumAsPlanObjectivesInner is a convenience function that returns ObjectivesEnum wrapped in PlanObjectivesInner
func ObjectivesEnumAsPlanObjectivesInner(v *ObjectivesEnum) PlanObjectivesInner {
	return PlanObjectivesInner{
		ObjectivesEnum: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PlanObjectivesInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CustomObjective
	err = newStrictDecoder(data).Decode(&dst.CustomObjective)
	if err == nil {
		jsonCustomObjective, _ := json.Marshal(dst.CustomObjective)
		if string(jsonCustomObjective) == "{}" { // empty struct
			dst.CustomObjective = nil
		} else {
			if err = validator.Validate(dst.CustomObjective); err != nil {
				dst.CustomObjective = nil
			} else {
				match++
			}
		}
	} else {
		dst.CustomObjective = nil
	}

	// try to unmarshal data into ObjectivesEnum
	err = newStrictDecoder(data).Decode(&dst.ObjectivesEnum)
	if err == nil {
		jsonObjectivesEnum, _ := json.Marshal(dst.ObjectivesEnum)
		if string(jsonObjectivesEnum) == "{}" { // empty struct
			dst.ObjectivesEnum = nil
		} else {
			if err = validator.Validate(dst.ObjectivesEnum); err != nil {
				dst.ObjectivesEnum = nil
			} else {
				match++
			}
		}
	} else {
		dst.ObjectivesEnum = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CustomObjective = nil
		dst.ObjectivesEnum = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PlanObjectivesInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PlanObjectivesInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PlanObjectivesInner) MarshalJSON() ([]byte, error) {
	if src.CustomObjective != nil {
		return json.Marshal(&src.CustomObjective)
	}

	if src.ObjectivesEnum != nil {
		return json.Marshal(&src.ObjectivesEnum)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PlanObjectivesInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CustomObjective != nil {
		return obj.CustomObjective
	}

	if obj.ObjectivesEnum != nil {
		return obj.ObjectivesEnum
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PlanObjectivesInner) GetActualInstanceValue() (interface{}) {
	if obj.CustomObjective != nil {
		return *obj.CustomObjective
	}

	if obj.ObjectivesEnum != nil {
		return *obj.ObjectivesEnum
	}

	// all schemas are nil
	return nil
}

type NullablePlanObjectivesInner struct {
	value *PlanObjectivesInner
	isSet bool
}

func (v NullablePlanObjectivesInner) Get() *PlanObjectivesInner {
	return v.value
}

func (v *NullablePlanObjectivesInner) Set(val *PlanObjectivesInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanObjectivesInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanObjectivesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanObjectivesInner(val *PlanObjectivesInner) *NullablePlanObjectivesInner {
	return &NullablePlanObjectivesInner{value: val, isSet: true}
}

func (v NullablePlanObjectivesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanObjectivesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


