/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PlanWebhook type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlanWebhook{}

// PlanWebhook struct for PlanWebhook
type PlanWebhook struct {
	// Universally Unique Identifier.
	Id *string `json:"id,omitempty" validate:"regexp=^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"`
	AgencyId *interface{} `json:"agencyId,omitempty"`
	// The secure webhook URL (must be https).
	Url *string `json:"url,omitempty"`
	// A map of header key-value pairs.
	Headers *map[string]string `json:"headers,omitempty"`
	// Specifies whether we should also provide the plan in the webhook's payload.
	WithPlan *bool `json:"withPlan,omitempty"`
	// Specifies whether the webhook is active or not.
	Active *bool `json:"active,omitempty"`
	// The webhook's creation date.
	CreatedAt *string `json:"createdAt,omitempty"`
	// The webhook's last update date.
	UpdatedAt *string `json:"updatedAt,omitempty"`
	// The webhook's expiration date.
	ExpiresAt *string `json:"expiresAt,omitempty"`
	PlanId *interface{} `json:"planId,omitempty"`
}

// NewPlanWebhook instantiates a new PlanWebhook object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanWebhook() *PlanWebhook {
	this := PlanWebhook{}
	var withPlan bool = false
	this.WithPlan = &withPlan
	var active bool = true
	this.Active = &active
	return &this
}

// NewPlanWebhookWithDefaults instantiates a new PlanWebhook object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanWebhookWithDefaults() *PlanWebhook {
	this := PlanWebhook{}
	var withPlan bool = false
	this.WithPlan = &withPlan
	var active bool = true
	this.Active = &active
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PlanWebhook) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanWebhook) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PlanWebhook) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PlanWebhook) SetId(v string) {
	o.Id = &v
}

// GetAgencyId returns the AgencyId field value if set, zero value otherwise.
func (o *PlanWebhook) GetAgencyId() interface{} {
	if o == nil || IsNil(o.AgencyId) {
		var ret interface{}
		return ret
	}
	return *o.AgencyId
}

// GetAgencyIdOk returns a tuple with the AgencyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanWebhook) GetAgencyIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.AgencyId) {
		return nil, false
	}
	return o.AgencyId, true
}

// HasAgencyId returns a boolean if a field has been set.
func (o *PlanWebhook) HasAgencyId() bool {
	if o != nil && !IsNil(o.AgencyId) {
		return true
	}

	return false
}

// SetAgencyId gets a reference to the given interface{} and assigns it to the AgencyId field.
func (o *PlanWebhook) SetAgencyId(v interface{}) {
	o.AgencyId = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *PlanWebhook) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanWebhook) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *PlanWebhook) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *PlanWebhook) SetUrl(v string) {
	o.Url = &v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *PlanWebhook) GetHeaders() map[string]string {
	if o == nil || IsNil(o.Headers) {
		var ret map[string]string
		return ret
	}
	return *o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanWebhook) GetHeadersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *PlanWebhook) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]string and assigns it to the Headers field.
func (o *PlanWebhook) SetHeaders(v map[string]string) {
	o.Headers = &v
}

// GetWithPlan returns the WithPlan field value if set, zero value otherwise.
func (o *PlanWebhook) GetWithPlan() bool {
	if o == nil || IsNil(o.WithPlan) {
		var ret bool
		return ret
	}
	return *o.WithPlan
}

// GetWithPlanOk returns a tuple with the WithPlan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanWebhook) GetWithPlanOk() (*bool, bool) {
	if o == nil || IsNil(o.WithPlan) {
		return nil, false
	}
	return o.WithPlan, true
}

// HasWithPlan returns a boolean if a field has been set.
func (o *PlanWebhook) HasWithPlan() bool {
	if o != nil && !IsNil(o.WithPlan) {
		return true
	}

	return false
}

// SetWithPlan gets a reference to the given bool and assigns it to the WithPlan field.
func (o *PlanWebhook) SetWithPlan(v bool) {
	o.WithPlan = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *PlanWebhook) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanWebhook) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *PlanWebhook) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *PlanWebhook) SetActive(v bool) {
	o.Active = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *PlanWebhook) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanWebhook) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *PlanWebhook) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *PlanWebhook) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *PlanWebhook) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanWebhook) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *PlanWebhook) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *PlanWebhook) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *PlanWebhook) GetExpiresAt() string {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret string
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanWebhook) GetExpiresAtOk() (*string, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *PlanWebhook) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given string and assigns it to the ExpiresAt field.
func (o *PlanWebhook) SetExpiresAt(v string) {
	o.ExpiresAt = &v
}

// GetPlanId returns the PlanId field value if set, zero value otherwise.
func (o *PlanWebhook) GetPlanId() interface{} {
	if o == nil || IsNil(o.PlanId) {
		var ret interface{}
		return ret
	}
	return *o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanWebhook) GetPlanIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.PlanId) {
		return nil, false
	}
	return o.PlanId, true
}

// HasPlanId returns a boolean if a field has been set.
func (o *PlanWebhook) HasPlanId() bool {
	if o != nil && !IsNil(o.PlanId) {
		return true
	}

	return false
}

// SetPlanId gets a reference to the given interface{} and assigns it to the PlanId field.
func (o *PlanWebhook) SetPlanId(v interface{}) {
	o.PlanId = &v
}

func (o PlanWebhook) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlanWebhook) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.AgencyId) {
		toSerialize["agencyId"] = o.AgencyId
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.WithPlan) {
		toSerialize["withPlan"] = o.WithPlan
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	if !IsNil(o.PlanId) {
		toSerialize["planId"] = o.PlanId
	}
	return toSerialize, nil
}

type NullablePlanWebhook struct {
	value *PlanWebhook
	isSet bool
}

func (v NullablePlanWebhook) Get() *PlanWebhook {
	return v.value
}

func (v *NullablePlanWebhook) Set(val *PlanWebhook) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanWebhook) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanWebhook) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanWebhook(val *PlanWebhook) *NullablePlanWebhook {
	return &NullablePlanWebhook{value: val, isSet: true}
}

func (v NullablePlanWebhook) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanWebhook) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


