/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PlanStatusVersion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlanStatusVersion{}

// PlanStatusVersion struct for PlanStatusVersion
type PlanStatusVersion struct {
	// The version currently waiting.
	WaitingVersion *int32 `json:"waitingVersion,omitempty"`
	// The version currently running.
	RunningVersion *int32 `json:"runningVersion,omitempty"`
}

// NewPlanStatusVersion instantiates a new PlanStatusVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanStatusVersion() *PlanStatusVersion {
	this := PlanStatusVersion{}
	return &this
}

// NewPlanStatusVersionWithDefaults instantiates a new PlanStatusVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanStatusVersionWithDefaults() *PlanStatusVersion {
	this := PlanStatusVersion{}
	return &this
}

// GetWaitingVersion returns the WaitingVersion field value if set, zero value otherwise.
func (o *PlanStatusVersion) GetWaitingVersion() int32 {
	if o == nil || IsNil(o.WaitingVersion) {
		var ret int32
		return ret
	}
	return *o.WaitingVersion
}

// GetWaitingVersionOk returns a tuple with the WaitingVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanStatusVersion) GetWaitingVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.WaitingVersion) {
		return nil, false
	}
	return o.WaitingVersion, true
}

// HasWaitingVersion returns a boolean if a field has been set.
func (o *PlanStatusVersion) HasWaitingVersion() bool {
	if o != nil && !IsNil(o.WaitingVersion) {
		return true
	}

	return false
}

// SetWaitingVersion gets a reference to the given int32 and assigns it to the WaitingVersion field.
func (o *PlanStatusVersion) SetWaitingVersion(v int32) {
	o.WaitingVersion = &v
}

// GetRunningVersion returns the RunningVersion field value if set, zero value otherwise.
func (o *PlanStatusVersion) GetRunningVersion() int32 {
	if o == nil || IsNil(o.RunningVersion) {
		var ret int32
		return ret
	}
	return *o.RunningVersion
}

// GetRunningVersionOk returns a tuple with the RunningVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanStatusVersion) GetRunningVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.RunningVersion) {
		return nil, false
	}
	return o.RunningVersion, true
}

// HasRunningVersion returns a boolean if a field has been set.
func (o *PlanStatusVersion) HasRunningVersion() bool {
	if o != nil && !IsNil(o.RunningVersion) {
		return true
	}

	return false
}

// SetRunningVersion gets a reference to the given int32 and assigns it to the RunningVersion field.
func (o *PlanStatusVersion) SetRunningVersion(v int32) {
	o.RunningVersion = &v
}

func (o PlanStatusVersion) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlanStatusVersion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.WaitingVersion) {
		toSerialize["waitingVersion"] = o.WaitingVersion
	}
	if !IsNil(o.RunningVersion) {
		toSerialize["runningVersion"] = o.RunningVersion
	}
	return toSerialize, nil
}

type NullablePlanStatusVersion struct {
	value *PlanStatusVersion
	isSet bool
}

func (v NullablePlanStatusVersion) Get() *PlanStatusVersion {
	return v.value
}

func (v *NullablePlanStatusVersion) Set(val *PlanStatusVersion) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanStatusVersion) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanStatusVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanStatusVersion(val *PlanStatusVersion) *NullablePlanStatusVersion {
	return &NullablePlanStatusVersion{value: val, isSet: true}
}

func (v NullablePlanStatusVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanStatusVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


