/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RemovalStrategyViolation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemovalStrategyViolation{}

// RemovalStrategyViolation Violation of a resource's RemovalStrategy constraint.
type RemovalStrategyViolation struct {
	Type string `json:"type"`
	// The name of the RemovalStrategy constraint the violation is linked to.
	Name *string `json:"name,omitempty"`
	RemovalStrategyType RemovalStrategyType `json:"removalStrategyType"`
}

type _RemovalStrategyViolation RemovalStrategyViolation

// NewRemovalStrategyViolation instantiates a new RemovalStrategyViolation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemovalStrategyViolation(type_ string, removalStrategyType RemovalStrategyType) *RemovalStrategyViolation {
	this := RemovalStrategyViolation{}
	this.Type = type_
	this.RemovalStrategyType = removalStrategyType
	return &this
}

// NewRemovalStrategyViolationWithDefaults instantiates a new RemovalStrategyViolation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemovalStrategyViolationWithDefaults() *RemovalStrategyViolation {
	this := RemovalStrategyViolation{}
	return &this
}

// GetType returns the Type field value
func (o *RemovalStrategyViolation) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RemovalStrategyViolation) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RemovalStrategyViolation) SetType(v string) {
	o.Type = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RemovalStrategyViolation) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemovalStrategyViolation) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RemovalStrategyViolation) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RemovalStrategyViolation) SetName(v string) {
	o.Name = &v
}

// GetRemovalStrategyType returns the RemovalStrategyType field value
func (o *RemovalStrategyViolation) GetRemovalStrategyType() RemovalStrategyType {
	if o == nil {
		var ret RemovalStrategyType
		return ret
	}

	return o.RemovalStrategyType
}

// GetRemovalStrategyTypeOk returns a tuple with the RemovalStrategyType field value
// and a boolean to check if the value has been set.
func (o *RemovalStrategyViolation) GetRemovalStrategyTypeOk() (*RemovalStrategyType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemovalStrategyType, true
}

// SetRemovalStrategyType sets field value
func (o *RemovalStrategyViolation) SetRemovalStrategyType(v RemovalStrategyType) {
	o.RemovalStrategyType = v
}

func (o RemovalStrategyViolation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemovalStrategyViolation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["removalStrategyType"] = o.RemovalStrategyType
	return toSerialize, nil
}

func (o *RemovalStrategyViolation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"removalStrategyType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRemovalStrategyViolation := _RemovalStrategyViolation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRemovalStrategyViolation)

	if err != nil {
		return err
	}

	*o = RemovalStrategyViolation(varRemovalStrategyViolation)

	return err
}

type NullableRemovalStrategyViolation struct {
	value *RemovalStrategyViolation
	isSet bool
}

func (v NullableRemovalStrategyViolation) Get() *RemovalStrategyViolation {
	return v.value
}

func (v *NullableRemovalStrategyViolation) Set(val *RemovalStrategyViolation) {
	v.value = val
	v.isSet = true
}

func (v NullableRemovalStrategyViolation) IsSet() bool {
	return v.isSet
}

func (v *NullableRemovalStrategyViolation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemovalStrategyViolation(val *RemovalStrategyViolation) *NullableRemovalStrategyViolation {
	return &NullableRemovalStrategyViolation{value: val, isSet: true}
}

func (v NullableRemovalStrategyViolation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemovalStrategyViolation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


