/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EnvelopedMFARequestTOTPOutputItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvelopedMFARequestTOTPOutputItem{}

// EnvelopedMFARequestTOTPOutputItem struct for EnvelopedMFARequestTOTPOutputItem
type EnvelopedMFARequestTOTPOutputItem struct {
	// A JSON Web Token with scope 'otp', to be used with an OTP (One-Time Password) value, valid for 10 minutes.
	OtpToken *string `json:"otpToken,omitempty"`
	TotpConfig NullableTOTPConfig `json:"totpConfig,omitempty"`
}

// NewEnvelopedMFARequestTOTPOutputItem instantiates a new EnvelopedMFARequestTOTPOutputItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvelopedMFARequestTOTPOutputItem() *EnvelopedMFARequestTOTPOutputItem {
	this := EnvelopedMFARequestTOTPOutputItem{}
	return &this
}

// NewEnvelopedMFARequestTOTPOutputItemWithDefaults instantiates a new EnvelopedMFARequestTOTPOutputItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvelopedMFARequestTOTPOutputItemWithDefaults() *EnvelopedMFARequestTOTPOutputItem {
	this := EnvelopedMFARequestTOTPOutputItem{}
	return &this
}

// GetOtpToken returns the OtpToken field value if set, zero value otherwise.
func (o *EnvelopedMFARequestTOTPOutputItem) GetOtpToken() string {
	if o == nil || IsNil(o.OtpToken) {
		var ret string
		return ret
	}
	return *o.OtpToken
}

// GetOtpTokenOk returns a tuple with the OtpToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvelopedMFARequestTOTPOutputItem) GetOtpTokenOk() (*string, bool) {
	if o == nil || IsNil(o.OtpToken) {
		return nil, false
	}
	return o.OtpToken, true
}

// HasOtpToken returns a boolean if a field has been set.
func (o *EnvelopedMFARequestTOTPOutputItem) HasOtpToken() bool {
	if o != nil && !IsNil(o.OtpToken) {
		return true
	}

	return false
}

// SetOtpToken gets a reference to the given string and assigns it to the OtpToken field.
func (o *EnvelopedMFARequestTOTPOutputItem) SetOtpToken(v string) {
	o.OtpToken = &v
}

// GetTotpConfig returns the TotpConfig field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EnvelopedMFARequestTOTPOutputItem) GetTotpConfig() TOTPConfig {
	if o == nil || IsNil(o.TotpConfig.Get()) {
		var ret TOTPConfig
		return ret
	}
	return *o.TotpConfig.Get()
}

// GetTotpConfigOk returns a tuple with the TotpConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnvelopedMFARequestTOTPOutputItem) GetTotpConfigOk() (*TOTPConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotpConfig.Get(), o.TotpConfig.IsSet()
}

// HasTotpConfig returns a boolean if a field has been set.
func (o *EnvelopedMFARequestTOTPOutputItem) HasTotpConfig() bool {
	if o != nil && o.TotpConfig.IsSet() {
		return true
	}

	return false
}

// SetTotpConfig gets a reference to the given NullableTOTPConfig and assigns it to the TotpConfig field.
func (o *EnvelopedMFARequestTOTPOutputItem) SetTotpConfig(v TOTPConfig) {
	o.TotpConfig.Set(&v)
}
// SetTotpConfigNil sets the value for TotpConfig to be an explicit nil
func (o *EnvelopedMFARequestTOTPOutputItem) SetTotpConfigNil() {
	o.TotpConfig.Set(nil)
}

// UnsetTotpConfig ensures that no value is present for TotpConfig, not even an explicit nil
func (o *EnvelopedMFARequestTOTPOutputItem) UnsetTotpConfig() {
	o.TotpConfig.Unset()
}

func (o EnvelopedMFARequestTOTPOutputItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvelopedMFARequestTOTPOutputItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OtpToken) {
		toSerialize["otpToken"] = o.OtpToken
	}
	if o.TotpConfig.IsSet() {
		toSerialize["totpConfig"] = o.TotpConfig.Get()
	}
	return toSerialize, nil
}

type NullableEnvelopedMFARequestTOTPOutputItem struct {
	value *EnvelopedMFARequestTOTPOutputItem
	isSet bool
}

func (v NullableEnvelopedMFARequestTOTPOutputItem) Get() *EnvelopedMFARequestTOTPOutputItem {
	return v.value
}

func (v *NullableEnvelopedMFARequestTOTPOutputItem) Set(val *EnvelopedMFARequestTOTPOutputItem) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvelopedMFARequestTOTPOutputItem) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvelopedMFARequestTOTPOutputItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvelopedMFARequestTOTPOutputItem(val *EnvelopedMFARequestTOTPOutputItem) *NullableEnvelopedMFARequestTOTPOutputItem {
	return &NullableEnvelopedMFARequestTOTPOutputItem{value: val, isSet: true}
}

func (v NullableEnvelopedMFARequestTOTPOutputItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvelopedMFARequestTOTPOutputItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


