/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AdditionalConstraintIncompatibleStopTags type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdditionalConstraintIncompatibleStopTags{}

// AdditionalConstraintIncompatibleStopTags Incompatibility between stop tags.
type AdditionalConstraintIncompatibleStopTags struct {
	Type string `json:"type"`
	Name *string `json:"name,omitempty"`
	// A pair of incompatible stop tags.
	StopTags []string `json:"stopTags"`
	ResourceTags []string `json:"resourceTags,omitempty"`
}

type _AdditionalConstraintIncompatibleStopTags AdditionalConstraintIncompatibleStopTags

// NewAdditionalConstraintIncompatibleStopTags instantiates a new AdditionalConstraintIncompatibleStopTags object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdditionalConstraintIncompatibleStopTags(type_ string, stopTags []string) *AdditionalConstraintIncompatibleStopTags {
	this := AdditionalConstraintIncompatibleStopTags{}
	this.Type = type_
	this.StopTags = stopTags
	return &this
}

// NewAdditionalConstraintIncompatibleStopTagsWithDefaults instantiates a new AdditionalConstraintIncompatibleStopTags object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdditionalConstraintIncompatibleStopTagsWithDefaults() *AdditionalConstraintIncompatibleStopTags {
	this := AdditionalConstraintIncompatibleStopTags{}
	return &this
}

// GetType returns the Type field value
func (o *AdditionalConstraintIncompatibleStopTags) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AdditionalConstraintIncompatibleStopTags) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AdditionalConstraintIncompatibleStopTags) SetType(v string) {
	o.Type = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AdditionalConstraintIncompatibleStopTags) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdditionalConstraintIncompatibleStopTags) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AdditionalConstraintIncompatibleStopTags) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AdditionalConstraintIncompatibleStopTags) SetName(v string) {
	o.Name = &v
}

// GetStopTags returns the StopTags field value
func (o *AdditionalConstraintIncompatibleStopTags) GetStopTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.StopTags
}

// GetStopTagsOk returns a tuple with the StopTags field value
// and a boolean to check if the value has been set.
func (o *AdditionalConstraintIncompatibleStopTags) GetStopTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StopTags, true
}

// SetStopTags sets field value
func (o *AdditionalConstraintIncompatibleStopTags) SetStopTags(v []string) {
	o.StopTags = v
}

// GetResourceTags returns the ResourceTags field value if set, zero value otherwise.
func (o *AdditionalConstraintIncompatibleStopTags) GetResourceTags() []string {
	if o == nil || IsNil(o.ResourceTags) {
		var ret []string
		return ret
	}
	return o.ResourceTags
}

// GetResourceTagsOk returns a tuple with the ResourceTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdditionalConstraintIncompatibleStopTags) GetResourceTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.ResourceTags) {
		return nil, false
	}
	return o.ResourceTags, true
}

// HasResourceTags returns a boolean if a field has been set.
func (o *AdditionalConstraintIncompatibleStopTags) HasResourceTags() bool {
	if o != nil && !IsNil(o.ResourceTags) {
		return true
	}

	return false
}

// SetResourceTags gets a reference to the given []string and assigns it to the ResourceTags field.
func (o *AdditionalConstraintIncompatibleStopTags) SetResourceTags(v []string) {
	o.ResourceTags = v
}

func (o AdditionalConstraintIncompatibleStopTags) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdditionalConstraintIncompatibleStopTags) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["stopTags"] = o.StopTags
	if !IsNil(o.ResourceTags) {
		toSerialize["resourceTags"] = o.ResourceTags
	}
	return toSerialize, nil
}

func (o *AdditionalConstraintIncompatibleStopTags) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"stopTags",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdditionalConstraintIncompatibleStopTags := _AdditionalConstraintIncompatibleStopTags{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdditionalConstraintIncompatibleStopTags)

	if err != nil {
		return err
	}

	*o = AdditionalConstraintIncompatibleStopTags(varAdditionalConstraintIncompatibleStopTags)

	return err
}

type NullableAdditionalConstraintIncompatibleStopTags struct {
	value *AdditionalConstraintIncompatibleStopTags
	isSet bool
}

func (v NullableAdditionalConstraintIncompatibleStopTags) Get() *AdditionalConstraintIncompatibleStopTags {
	return v.value
}

func (v *NullableAdditionalConstraintIncompatibleStopTags) Set(val *AdditionalConstraintIncompatibleStopTags) {
	v.value = val
	v.isSet = true
}

func (v NullableAdditionalConstraintIncompatibleStopTags) IsSet() bool {
	return v.isSet
}

func (v *NullableAdditionalConstraintIncompatibleStopTags) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdditionalConstraintIncompatibleStopTags(val *AdditionalConstraintIncompatibleStopTags) *NullableAdditionalConstraintIncompatibleStopTags {
	return &NullableAdditionalConstraintIncompatibleStopTags{value: val, isSet: true}
}

func (v NullableAdditionalConstraintIncompatibleStopTags) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdditionalConstraintIncompatibleStopTags) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


