/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ResourceMode the model 'ResourceMode'
type ResourceMode string

// List of ResourceMode
const (
	RESOURCEMODE_FREE ResourceMode = "free"
	RESOURCEMODE_FIXED ResourceMode = "fixed"
)

// All allowed values of ResourceMode enum
var AllowedResourceModeEnumValues = []ResourceMode{
	"free",
	"fixed",
}

func (v *ResourceMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ResourceMode(value)
	for _, existing := range AllowedResourceModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ResourceMode", value)
}

// NewResourceModeFromValue returns a pointer to a valid ResourceMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewResourceModeFromValue(v string) (*ResourceMode, error) {
	ev := ResourceMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ResourceMode: valid values are %v", v, AllowedResourceModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ResourceMode) IsValid() bool {
	for _, existing := range AllowedResourceModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ResourceMode value
func (v ResourceMode) Ptr() *ResourceMode {
	return &v
}

type NullableResourceMode struct {
	value *ResourceMode
	isSet bool
}

func (v NullableResourceMode) Get() *ResourceMode {
	return v.value
}

func (v *NullableResourceMode) Set(val *ResourceMode) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceMode) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceMode(val *ResourceMode) *NullableResourceMode {
	return &NullableResourceMode{value: val, isSet: true}
}

func (v NullableResourceMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

