/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SMAOrder type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SMAOrder{}

// SMAOrder struct for SMAOrder
type SMAOrder struct {
	// Order ids must be unique within a plan.
	Id string `json:"id" validate:"regexp=^[a-zA-Z0-9-._~:@!$,]+$"`
	Properties *map[string]string `json:"properties,omitempty"`
	// 0 by default, can be negative.
	Priority *int32 `json:"priority,omitempty"`
	Optional *bool `json:"optional,omitempty"`
	RequiredSkills []string `json:"requiredSkills,omitempty"`
	Stops []Stop `json:"stops"`
	SuccessiveStops *bool `json:"successiveStops,omitempty"`
	// A period of time, expressed in the ISO8601 **duration** format.
	MaxStopSpan *string `json:"maxStopSpan,omitempty" validate:"regexp=^P(\\\\d+Y)?(\\\\d+M)?(\\\\d+W)?(\\\\d+D)?(T(\\\\d+H)?(\\\\d+M)?(\\\\d+S)?)?$"`
}

type _SMAOrder SMAOrder

// NewSMAOrder instantiates a new SMAOrder object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSMAOrder(id string, stops []Stop) *SMAOrder {
	this := SMAOrder{}
	this.Id = id
	var priority int32 = 0
	this.Priority = &priority
	this.Stops = stops
	return &this
}

// NewSMAOrderWithDefaults instantiates a new SMAOrder object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSMAOrderWithDefaults() *SMAOrder {
	this := SMAOrder{}
	var priority int32 = 0
	this.Priority = &priority
	return &this
}

// GetId returns the Id field value
func (o *SMAOrder) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SMAOrder) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SMAOrder) SetId(v string) {
	o.Id = v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *SMAOrder) GetProperties() map[string]string {
	if o == nil || IsNil(o.Properties) {
		var ret map[string]string
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SMAOrder) GetPropertiesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *SMAOrder) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]string and assigns it to the Properties field.
func (o *SMAOrder) SetProperties(v map[string]string) {
	o.Properties = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *SMAOrder) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SMAOrder) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *SMAOrder) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *SMAOrder) SetPriority(v int32) {
	o.Priority = &v
}

// GetOptional returns the Optional field value if set, zero value otherwise.
func (o *SMAOrder) GetOptional() bool {
	if o == nil || IsNil(o.Optional) {
		var ret bool
		return ret
	}
	return *o.Optional
}

// GetOptionalOk returns a tuple with the Optional field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SMAOrder) GetOptionalOk() (*bool, bool) {
	if o == nil || IsNil(o.Optional) {
		return nil, false
	}
	return o.Optional, true
}

// HasOptional returns a boolean if a field has been set.
func (o *SMAOrder) HasOptional() bool {
	if o != nil && !IsNil(o.Optional) {
		return true
	}

	return false
}

// SetOptional gets a reference to the given bool and assigns it to the Optional field.
func (o *SMAOrder) SetOptional(v bool) {
	o.Optional = &v
}

// GetRequiredSkills returns the RequiredSkills field value if set, zero value otherwise.
func (o *SMAOrder) GetRequiredSkills() []string {
	if o == nil || IsNil(o.RequiredSkills) {
		var ret []string
		return ret
	}
	return o.RequiredSkills
}

// GetRequiredSkillsOk returns a tuple with the RequiredSkills field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SMAOrder) GetRequiredSkillsOk() ([]string, bool) {
	if o == nil || IsNil(o.RequiredSkills) {
		return nil, false
	}
	return o.RequiredSkills, true
}

// HasRequiredSkills returns a boolean if a field has been set.
func (o *SMAOrder) HasRequiredSkills() bool {
	if o != nil && !IsNil(o.RequiredSkills) {
		return true
	}

	return false
}

// SetRequiredSkills gets a reference to the given []string and assigns it to the RequiredSkills field.
func (o *SMAOrder) SetRequiredSkills(v []string) {
	o.RequiredSkills = v
}

// GetStops returns the Stops field value
func (o *SMAOrder) GetStops() []Stop {
	if o == nil {
		var ret []Stop
		return ret
	}

	return o.Stops
}

// GetStopsOk returns a tuple with the Stops field value
// and a boolean to check if the value has been set.
func (o *SMAOrder) GetStopsOk() ([]Stop, bool) {
	if o == nil {
		return nil, false
	}
	return o.Stops, true
}

// SetStops sets field value
func (o *SMAOrder) SetStops(v []Stop) {
	o.Stops = v
}

// GetSuccessiveStops returns the SuccessiveStops field value if set, zero value otherwise.
func (o *SMAOrder) GetSuccessiveStops() bool {
	if o == nil || IsNil(o.SuccessiveStops) {
		var ret bool
		return ret
	}
	return *o.SuccessiveStops
}

// GetSuccessiveStopsOk returns a tuple with the SuccessiveStops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SMAOrder) GetSuccessiveStopsOk() (*bool, bool) {
	if o == nil || IsNil(o.SuccessiveStops) {
		return nil, false
	}
	return o.SuccessiveStops, true
}

// HasSuccessiveStops returns a boolean if a field has been set.
func (o *SMAOrder) HasSuccessiveStops() bool {
	if o != nil && !IsNil(o.SuccessiveStops) {
		return true
	}

	return false
}

// SetSuccessiveStops gets a reference to the given bool and assigns it to the SuccessiveStops field.
func (o *SMAOrder) SetSuccessiveStops(v bool) {
	o.SuccessiveStops = &v
}

// GetMaxStopSpan returns the MaxStopSpan field value if set, zero value otherwise.
func (o *SMAOrder) GetMaxStopSpan() string {
	if o == nil || IsNil(o.MaxStopSpan) {
		var ret string
		return ret
	}
	return *o.MaxStopSpan
}

// GetMaxStopSpanOk returns a tuple with the MaxStopSpan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SMAOrder) GetMaxStopSpanOk() (*string, bool) {
	if o == nil || IsNil(o.MaxStopSpan) {
		return nil, false
	}
	return o.MaxStopSpan, true
}

// HasMaxStopSpan returns a boolean if a field has been set.
func (o *SMAOrder) HasMaxStopSpan() bool {
	if o != nil && !IsNil(o.MaxStopSpan) {
		return true
	}

	return false
}

// SetMaxStopSpan gets a reference to the given string and assigns it to the MaxStopSpan field.
func (o *SMAOrder) SetMaxStopSpan(v string) {
	o.MaxStopSpan = &v
}

func (o SMAOrder) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SMAOrder) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.Optional) {
		toSerialize["optional"] = o.Optional
	}
	if !IsNil(o.RequiredSkills) {
		toSerialize["requiredSkills"] = o.RequiredSkills
	}
	toSerialize["stops"] = o.Stops
	if !IsNil(o.SuccessiveStops) {
		toSerialize["successiveStops"] = o.SuccessiveStops
	}
	if !IsNil(o.MaxStopSpan) {
		toSerialize["maxStopSpan"] = o.MaxStopSpan
	}
	return toSerialize, nil
}

func (o *SMAOrder) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"stops",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSMAOrder := _SMAOrder{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSMAOrder)

	if err != nil {
		return err
	}

	*o = SMAOrder(varSMAOrder)

	return err
}

type NullableSMAOrder struct {
	value *SMAOrder
	isSet bool
}

func (v NullableSMAOrder) Get() *SMAOrder {
	return v.value
}

func (v *NullableSMAOrder) Set(val *SMAOrder) {
	v.value = val
	v.isSet = true
}

func (v NullableSMAOrder) IsSet() bool {
	return v.isSet
}

func (v *NullableSMAOrder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSMAOrder(val *SMAOrder) *NullableSMAOrder {
	return &NullableSMAOrder{value: val, isSet: true}
}

func (v NullableSMAOrder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSMAOrder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


