/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MFAConfigRegenerateBackupCodes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MFAConfigRegenerateBackupCodes{}

// MFAConfigRegenerateBackupCodes A request to regenerate the MFA's backup codes.
type MFAConfigRegenerateBackupCodes struct {
	Password Password `json:"password"`
}

type _MFAConfigRegenerateBackupCodes MFAConfigRegenerateBackupCodes

// NewMFAConfigRegenerateBackupCodes instantiates a new MFAConfigRegenerateBackupCodes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMFAConfigRegenerateBackupCodes(password Password) *MFAConfigRegenerateBackupCodes {
	this := MFAConfigRegenerateBackupCodes{}
	this.Password = password
	return &this
}

// NewMFAConfigRegenerateBackupCodesWithDefaults instantiates a new MFAConfigRegenerateBackupCodes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMFAConfigRegenerateBackupCodesWithDefaults() *MFAConfigRegenerateBackupCodes {
	this := MFAConfigRegenerateBackupCodes{}
	return &this
}

// GetPassword returns the Password field value
func (o *MFAConfigRegenerateBackupCodes) GetPassword() Password {
	if o == nil {
		var ret Password
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *MFAConfigRegenerateBackupCodes) GetPasswordOk() (*Password, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *MFAConfigRegenerateBackupCodes) SetPassword(v Password) {
	o.Password = v
}

func (o MFAConfigRegenerateBackupCodes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MFAConfigRegenerateBackupCodes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *MFAConfigRegenerateBackupCodes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMFAConfigRegenerateBackupCodes := _MFAConfigRegenerateBackupCodes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMFAConfigRegenerateBackupCodes)

	if err != nil {
		return err
	}

	*o = MFAConfigRegenerateBackupCodes(varMFAConfigRegenerateBackupCodes)

	return err
}

type NullableMFAConfigRegenerateBackupCodes struct {
	value *MFAConfigRegenerateBackupCodes
	isSet bool
}

func (v NullableMFAConfigRegenerateBackupCodes) Get() *MFAConfigRegenerateBackupCodes {
	return v.value
}

func (v *NullableMFAConfigRegenerateBackupCodes) Set(val *MFAConfigRegenerateBackupCodes) {
	v.value = val
	v.isSet = true
}

func (v NullableMFAConfigRegenerateBackupCodes) IsSet() bool {
	return v.isSet
}

func (v *NullableMFAConfigRegenerateBackupCodes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMFAConfigRegenerateBackupCodes(val *MFAConfigRegenerateBackupCodes) *NullableMFAConfigRegenerateBackupCodes {
	return &NullableMFAConfigRegenerateBackupCodes{value: val, isSet: true}
}

func (v NullableMFAConfigRegenerateBackupCodes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMFAConfigRegenerateBackupCodes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


