/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AlternativesStop type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlternativesStop{}

// AlternativesStop A stop composed of different alternative single stops.
type AlternativesStop struct {
	Type string `json:"type"`
	Alternatives []SingleStop `json:"alternatives"`
}

type _AlternativesStop AlternativesStop

// NewAlternativesStop instantiates a new AlternativesStop object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlternativesStop(type_ string, alternatives []SingleStop) *AlternativesStop {
	this := AlternativesStop{}
	this.Type = type_
	this.Alternatives = alternatives
	return &this
}

// NewAlternativesStopWithDefaults instantiates a new AlternativesStop object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlternativesStopWithDefaults() *AlternativesStop {
	this := AlternativesStop{}
	return &this
}

// GetType returns the Type field value
func (o *AlternativesStop) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AlternativesStop) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AlternativesStop) SetType(v string) {
	o.Type = v
}

// GetAlternatives returns the Alternatives field value
func (o *AlternativesStop) GetAlternatives() []SingleStop {
	if o == nil {
		var ret []SingleStop
		return ret
	}

	return o.Alternatives
}

// GetAlternativesOk returns a tuple with the Alternatives field value
// and a boolean to check if the value has been set.
func (o *AlternativesStop) GetAlternativesOk() ([]SingleStop, bool) {
	if o == nil {
		return nil, false
	}
	return o.Alternatives, true
}

// SetAlternatives sets field value
func (o *AlternativesStop) SetAlternatives(v []SingleStop) {
	o.Alternatives = v
}

func (o AlternativesStop) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlternativesStop) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["alternatives"] = o.Alternatives
	return toSerialize, nil
}

func (o *AlternativesStop) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"alternatives",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAlternativesStop := _AlternativesStop{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAlternativesStop)

	if err != nil {
		return err
	}

	*o = AlternativesStop(varAlternativesStop)

	return err
}

type NullableAlternativesStop struct {
	value *AlternativesStop
	isSet bool
}

func (v NullableAlternativesStop) Get() *AlternativesStop {
	return v.value
}

func (v *NullableAlternativesStop) Set(val *AlternativesStop) {
	v.value = val
	v.isSet = true
}

func (v NullableAlternativesStop) IsSet() bool {
	return v.isSet
}

func (v *NullableAlternativesStop) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlternativesStop(val *AlternativesStop) *NullableAlternativesStop {
	return &NullableAlternativesStop{value: val, isSet: true}
}

func (v NullableAlternativesStop) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlternativesStop) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


