/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AssignmentBreak type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssignmentBreak{}

// AssignmentBreak struct for AssignmentBreak
type AssignmentBreak struct {
	Type string `json:"type"`
	Status *AssignmentStatus `json:"status,omitempty"`
	// A full calendar date time, expressed in the ISO8601 **date** format: YYYY-MM-DDThh:mm:ssZ.
	ArrivalTime string `json:"arrivalTime"`
	// A full calendar date time, expressed in the ISO8601 **date** format: YYYY-MM-DDThh:mm:ssZ.
	DepartureTime string `json:"departureTime"`
}

type _AssignmentBreak AssignmentBreak

// NewAssignmentBreak instantiates a new AssignmentBreak object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssignmentBreak(type_ string, arrivalTime string, departureTime string) *AssignmentBreak {
	this := AssignmentBreak{}
	this.Type = type_
	var status AssignmentStatus = ASSIGNMENTSTATUS_FIXED
	this.Status = &status
	this.ArrivalTime = arrivalTime
	this.DepartureTime = departureTime
	return &this
}

// NewAssignmentBreakWithDefaults instantiates a new AssignmentBreak object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssignmentBreakWithDefaults() *AssignmentBreak {
	this := AssignmentBreak{}
	var status AssignmentStatus = ASSIGNMENTSTATUS_FIXED
	this.Status = &status
	return &this
}

// GetType returns the Type field value
func (o *AssignmentBreak) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AssignmentBreak) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AssignmentBreak) SetType(v string) {
	o.Type = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AssignmentBreak) GetStatus() AssignmentStatus {
	if o == nil || IsNil(o.Status) {
		var ret AssignmentStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignmentBreak) GetStatusOk() (*AssignmentStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AssignmentBreak) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given AssignmentStatus and assigns it to the Status field.
func (o *AssignmentBreak) SetStatus(v AssignmentStatus) {
	o.Status = &v
}

// GetArrivalTime returns the ArrivalTime field value
func (o *AssignmentBreak) GetArrivalTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ArrivalTime
}

// GetArrivalTimeOk returns a tuple with the ArrivalTime field value
// and a boolean to check if the value has been set.
func (o *AssignmentBreak) GetArrivalTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArrivalTime, true
}

// SetArrivalTime sets field value
func (o *AssignmentBreak) SetArrivalTime(v string) {
	o.ArrivalTime = v
}

// GetDepartureTime returns the DepartureTime field value
func (o *AssignmentBreak) GetDepartureTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DepartureTime
}

// GetDepartureTimeOk returns a tuple with the DepartureTime field value
// and a boolean to check if the value has been set.
func (o *AssignmentBreak) GetDepartureTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DepartureTime, true
}

// SetDepartureTime sets field value
func (o *AssignmentBreak) SetDepartureTime(v string) {
	o.DepartureTime = v
}

func (o AssignmentBreak) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssignmentBreak) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	toSerialize["arrivalTime"] = o.ArrivalTime
	toSerialize["departureTime"] = o.DepartureTime
	return toSerialize, nil
}

func (o *AssignmentBreak) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"arrivalTime",
		"departureTime",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAssignmentBreak := _AssignmentBreak{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAssignmentBreak)

	if err != nil {
		return err
	}

	*o = AssignmentBreak(varAssignmentBreak)

	return err
}

type NullableAssignmentBreak struct {
	value *AssignmentBreak
	isSet bool
}

func (v NullableAssignmentBreak) Get() *AssignmentBreak {
	return v.value
}

func (v *NullableAssignmentBreak) Set(val *AssignmentBreak) {
	v.value = val
	v.isSet = true
}

func (v NullableAssignmentBreak) IsSet() bool {
	return v.isSet
}

func (v *NullableAssignmentBreak) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssignmentBreak(val *AssignmentBreak) *NullableAssignmentBreak {
	return &NullableAssignmentBreak{value: val, isSet: true}
}

func (v NullableAssignmentBreak) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssignmentBreak) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


