/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkingTimeWindowViolation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkingTimeWindowViolation{}

// WorkingTimeWindowViolation Violation of a resource's TimeWindow constraint.
type WorkingTimeWindowViolation struct {
	Type string `json:"type"`
	// The delay that exceeds the resource's TimeWindow.
	Delay string `json:"delay" validate:"regexp=^P(\\\\d+Y)?(\\\\d+M)?(\\\\d+W)?(\\\\d+D)?(T(\\\\d+H)?(\\\\d+M)?(\\\\d+S)?)?$"`
}

type _WorkingTimeWindowViolation WorkingTimeWindowViolation

// NewWorkingTimeWindowViolation instantiates a new WorkingTimeWindowViolation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkingTimeWindowViolation(type_ string, delay string) *WorkingTimeWindowViolation {
	this := WorkingTimeWindowViolation{}
	this.Type = type_
	this.Delay = delay
	return &this
}

// NewWorkingTimeWindowViolationWithDefaults instantiates a new WorkingTimeWindowViolation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkingTimeWindowViolationWithDefaults() *WorkingTimeWindowViolation {
	this := WorkingTimeWindowViolation{}
	return &this
}

// GetType returns the Type field value
func (o *WorkingTimeWindowViolation) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *WorkingTimeWindowViolation) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *WorkingTimeWindowViolation) SetType(v string) {
	o.Type = v
}

// GetDelay returns the Delay field value
func (o *WorkingTimeWindowViolation) GetDelay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Delay
}

// GetDelayOk returns a tuple with the Delay field value
// and a boolean to check if the value has been set.
func (o *WorkingTimeWindowViolation) GetDelayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Delay, true
}

// SetDelay sets field value
func (o *WorkingTimeWindowViolation) SetDelay(v string) {
	o.Delay = v
}

func (o WorkingTimeWindowViolation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkingTimeWindowViolation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["delay"] = o.Delay
	return toSerialize, nil
}

func (o *WorkingTimeWindowViolation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"delay",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkingTimeWindowViolation := _WorkingTimeWindowViolation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkingTimeWindowViolation)

	if err != nil {
		return err
	}

	*o = WorkingTimeWindowViolation(varWorkingTimeWindowViolation)

	return err
}

type NullableWorkingTimeWindowViolation struct {
	value *WorkingTimeWindowViolation
	isSet bool
}

func (v NullableWorkingTimeWindowViolation) Get() *WorkingTimeWindowViolation {
	return v.value
}

func (v *NullableWorkingTimeWindowViolation) Set(val *WorkingTimeWindowViolation) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkingTimeWindowViolation) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkingTimeWindowViolation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkingTimeWindowViolation(val *WorkingTimeWindowViolation) *NullableWorkingTimeWindowViolation {
	return &NullableWorkingTimeWindowViolation{value: val, isSet: true}
}

func (v NullableWorkingTimeWindowViolation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkingTimeWindowViolation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


