/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EndViolation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndViolation{}

// EndViolation Violation of a warehouse Constraint at the end of a Tour.
type EndViolation struct {
	Type string `json:"type"`
	// The idx of the waypoint the violation applies to.
	WayPointIndex *int32 `json:"wayPointIndex,omitempty"`
}

type _EndViolation EndViolation

// NewEndViolation instantiates a new EndViolation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndViolation(type_ string) *EndViolation {
	this := EndViolation{}
	this.Type = type_
	return &this
}

// NewEndViolationWithDefaults instantiates a new EndViolation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndViolationWithDefaults() *EndViolation {
	this := EndViolation{}
	return &this
}

// GetType returns the Type field value
func (o *EndViolation) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EndViolation) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EndViolation) SetType(v string) {
	o.Type = v
}

// GetWayPointIndex returns the WayPointIndex field value if set, zero value otherwise.
func (o *EndViolation) GetWayPointIndex() int32 {
	if o == nil || IsNil(o.WayPointIndex) {
		var ret int32
		return ret
	}
	return *o.WayPointIndex
}

// GetWayPointIndexOk returns a tuple with the WayPointIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndViolation) GetWayPointIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.WayPointIndex) {
		return nil, false
	}
	return o.WayPointIndex, true
}

// HasWayPointIndex returns a boolean if a field has been set.
func (o *EndViolation) HasWayPointIndex() bool {
	if o != nil && !IsNil(o.WayPointIndex) {
		return true
	}

	return false
}

// SetWayPointIndex gets a reference to the given int32 and assigns it to the WayPointIndex field.
func (o *EndViolation) SetWayPointIndex(v int32) {
	o.WayPointIndex = &v
}

func (o EndViolation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndViolation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.WayPointIndex) {
		toSerialize["wayPointIndex"] = o.WayPointIndex
	}
	return toSerialize, nil
}

func (o *EndViolation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEndViolation := _EndViolation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEndViolation)

	if err != nil {
		return err
	}

	*o = EndViolation(varEndViolation)

	return err
}

type NullableEndViolation struct {
	value *EndViolation
	isSet bool
}

func (v NullableEndViolation) Get() *EndViolation {
	return v.value
}

func (v *NullableEndViolation) Set(val *EndViolation) {
	v.value = val
	v.isSet = true
}

func (v NullableEndViolation) IsSet() bool {
	return v.isSet
}

func (v *NullableEndViolation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndViolation(val *EndViolation) *NullableEndViolation {
	return &NullableEndViolation{value: val, isSet: true}
}

func (v NullableEndViolation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndViolation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


