/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EnvelopedAgencyWebhooks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvelopedAgencyWebhooks{}

// EnvelopedAgencyWebhooks struct for EnvelopedAgencyWebhooks
type EnvelopedAgencyWebhooks struct {
	Items []AgencyWebhook `json:"items,omitempty"`
	AgencyId *interface{} `json:"agencyId,omitempty"`
}

// NewEnvelopedAgencyWebhooks instantiates a new EnvelopedAgencyWebhooks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvelopedAgencyWebhooks() *EnvelopedAgencyWebhooks {
	this := EnvelopedAgencyWebhooks{}
	return &this
}

// NewEnvelopedAgencyWebhooksWithDefaults instantiates a new EnvelopedAgencyWebhooks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvelopedAgencyWebhooksWithDefaults() *EnvelopedAgencyWebhooks {
	this := EnvelopedAgencyWebhooks{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *EnvelopedAgencyWebhooks) GetItems() []AgencyWebhook {
	if o == nil || IsNil(o.Items) {
		var ret []AgencyWebhook
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvelopedAgencyWebhooks) GetItemsOk() ([]AgencyWebhook, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *EnvelopedAgencyWebhooks) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []AgencyWebhook and assigns it to the Items field.
func (o *EnvelopedAgencyWebhooks) SetItems(v []AgencyWebhook) {
	o.Items = v
}

// GetAgencyId returns the AgencyId field value if set, zero value otherwise.
func (o *EnvelopedAgencyWebhooks) GetAgencyId() interface{} {
	if o == nil || IsNil(o.AgencyId) {
		var ret interface{}
		return ret
	}
	return *o.AgencyId
}

// GetAgencyIdOk returns a tuple with the AgencyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvelopedAgencyWebhooks) GetAgencyIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.AgencyId) {
		return nil, false
	}
	return o.AgencyId, true
}

// HasAgencyId returns a boolean if a field has been set.
func (o *EnvelopedAgencyWebhooks) HasAgencyId() bool {
	if o != nil && !IsNil(o.AgencyId) {
		return true
	}

	return false
}

// SetAgencyId gets a reference to the given interface{} and assigns it to the AgencyId field.
func (o *EnvelopedAgencyWebhooks) SetAgencyId(v interface{}) {
	o.AgencyId = &v
}

func (o EnvelopedAgencyWebhooks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvelopedAgencyWebhooks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.AgencyId) {
		toSerialize["agencyId"] = o.AgencyId
	}
	return toSerialize, nil
}

type NullableEnvelopedAgencyWebhooks struct {
	value *EnvelopedAgencyWebhooks
	isSet bool
}

func (v NullableEnvelopedAgencyWebhooks) Get() *EnvelopedAgencyWebhooks {
	return v.value
}

func (v *NullableEnvelopedAgencyWebhooks) Set(val *EnvelopedAgencyWebhooks) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvelopedAgencyWebhooks) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvelopedAgencyWebhooks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvelopedAgencyWebhooks(val *EnvelopedAgencyWebhooks) *NullableEnvelopedAgencyWebhooks {
	return &NullableEnvelopedAgencyWebhooks{value: val, isSet: true}
}

func (v NullableEnvelopedAgencyWebhooks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvelopedAgencyWebhooks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


