/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebhookCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookCreate{}

// WebhookCreate struct for WebhookCreate
type WebhookCreate struct {
	// The secure webhook URL (must be https).
	Url string `json:"url"`
	// A map of header key-value pairs.
	Headers *map[string]string `json:"headers,omitempty"`
	// Specifies whether we should also provide the plan in the webhook's payload.
	WithPlan *bool `json:"withPlan,omitempty"`
	// Defines the webhook's time to live in iso 8601 duration format. The value should be at least 30 minutes and at most 14 days. 
	Ttl *string `json:"ttl,omitempty" validate:"regexp=^P(\\\\d+Y)?(\\\\d+M)?(\\\\d+W)?(\\\\d+D)?(T(\\\\d+H)?(\\\\d+M)?(\\\\d+S)?)?$"`
}

type _WebhookCreate WebhookCreate

// NewWebhookCreate instantiates a new WebhookCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookCreate(url string) *WebhookCreate {
	this := WebhookCreate{}
	this.Url = url
	var withPlan bool = false
	this.WithPlan = &withPlan
	var ttl string = "PT30M"
	this.Ttl = &ttl
	return &this
}

// NewWebhookCreateWithDefaults instantiates a new WebhookCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookCreateWithDefaults() *WebhookCreate {
	this := WebhookCreate{}
	var withPlan bool = false
	this.WithPlan = &withPlan
	var ttl string = "PT30M"
	this.Ttl = &ttl
	return &this
}

// GetUrl returns the Url field value
func (o *WebhookCreate) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhookCreate) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhookCreate) SetUrl(v string) {
	o.Url = v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *WebhookCreate) GetHeaders() map[string]string {
	if o == nil || IsNil(o.Headers) {
		var ret map[string]string
		return ret
	}
	return *o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookCreate) GetHeadersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *WebhookCreate) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]string and assigns it to the Headers field.
func (o *WebhookCreate) SetHeaders(v map[string]string) {
	o.Headers = &v
}

// GetWithPlan returns the WithPlan field value if set, zero value otherwise.
func (o *WebhookCreate) GetWithPlan() bool {
	if o == nil || IsNil(o.WithPlan) {
		var ret bool
		return ret
	}
	return *o.WithPlan
}

// GetWithPlanOk returns a tuple with the WithPlan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookCreate) GetWithPlanOk() (*bool, bool) {
	if o == nil || IsNil(o.WithPlan) {
		return nil, false
	}
	return o.WithPlan, true
}

// HasWithPlan returns a boolean if a field has been set.
func (o *WebhookCreate) HasWithPlan() bool {
	if o != nil && !IsNil(o.WithPlan) {
		return true
	}

	return false
}

// SetWithPlan gets a reference to the given bool and assigns it to the WithPlan field.
func (o *WebhookCreate) SetWithPlan(v bool) {
	o.WithPlan = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *WebhookCreate) GetTtl() string {
	if o == nil || IsNil(o.Ttl) {
		var ret string
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookCreate) GetTtlOk() (*string, bool) {
	if o == nil || IsNil(o.Ttl) {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *WebhookCreate) HasTtl() bool {
	if o != nil && !IsNil(o.Ttl) {
		return true
	}

	return false
}

// SetTtl gets a reference to the given string and assigns it to the Ttl field.
func (o *WebhookCreate) SetTtl(v string) {
	o.Ttl = &v
}

func (o WebhookCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.WithPlan) {
		toSerialize["withPlan"] = o.WithPlan
	}
	if !IsNil(o.Ttl) {
		toSerialize["ttl"] = o.Ttl
	}
	return toSerialize, nil
}

func (o *WebhookCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookCreate := _WebhookCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookCreate)

	if err != nil {
		return err
	}

	*o = WebhookCreate(varWebhookCreate)

	return err
}

type NullableWebhookCreate struct {
	value *WebhookCreate
	isSet bool
}

func (v NullableWebhookCreate) Get() *WebhookCreate {
	return v.value
}

func (v *NullableWebhookCreate) Set(val *WebhookCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookCreate(val *WebhookCreate) *NullableWebhookCreate {
	return &NullableWebhookCreate{value: val, isSet: true}
}

func (v NullableWebhookCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


