/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// RegexIdValidationOrEmpty - struct for RegexIdValidationOrEmpty
type RegexIdValidationOrEmpty struct {
	String *string
}

// stringAsRegexIdValidationOrEmpty is a convenience function that returns string wrapped in RegexIdValidationOrEmpty
func StringAsRegexIdValidationOrEmpty(v *string) RegexIdValidationOrEmpty {
	return RegexIdValidationOrEmpty{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *RegexIdValidationOrEmpty) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(RegexIdValidationOrEmpty)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(RegexIdValidationOrEmpty)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RegexIdValidationOrEmpty) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *RegexIdValidationOrEmpty) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj RegexIdValidationOrEmpty) GetActualInstanceValue() (interface{}) {
	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableRegexIdValidationOrEmpty struct {
	value *RegexIdValidationOrEmpty
	isSet bool
}

func (v NullableRegexIdValidationOrEmpty) Get() *RegexIdValidationOrEmpty {
	return v.value
}

func (v *NullableRegexIdValidationOrEmpty) Set(val *RegexIdValidationOrEmpty) {
	v.value = val
	v.isSet = true
}

func (v NullableRegexIdValidationOrEmpty) IsSet() bool {
	return v.isSet
}

func (v *NullableRegexIdValidationOrEmpty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegexIdValidationOrEmpty(val *RegexIdValidationOrEmpty) *NullableRegexIdValidationOrEmpty {
	return &NullableRegexIdValidationOrEmpty{value: val, isSet: true}
}

func (v NullableRegexIdValidationOrEmpty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegexIdValidationOrEmpty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


