/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EnvelopedPlainCountry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvelopedPlainCountry{}

// EnvelopedPlainCountry struct for EnvelopedPlainCountry
type EnvelopedPlainCountry struct {
	Item *PlainCountry `json:"item,omitempty"`
}

// NewEnvelopedPlainCountry instantiates a new EnvelopedPlainCountry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvelopedPlainCountry() *EnvelopedPlainCountry {
	this := EnvelopedPlainCountry{}
	return &this
}

// NewEnvelopedPlainCountryWithDefaults instantiates a new EnvelopedPlainCountry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvelopedPlainCountryWithDefaults() *EnvelopedPlainCountry {
	this := EnvelopedPlainCountry{}
	return &this
}

// GetItem returns the Item field value if set, zero value otherwise.
func (o *EnvelopedPlainCountry) GetItem() PlainCountry {
	if o == nil || IsNil(o.Item) {
		var ret PlainCountry
		return ret
	}
	return *o.Item
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvelopedPlainCountry) GetItemOk() (*PlainCountry, bool) {
	if o == nil || IsNil(o.Item) {
		return nil, false
	}
	return o.Item, true
}

// HasItem returns a boolean if a field has been set.
func (o *EnvelopedPlainCountry) HasItem() bool {
	if o != nil && !IsNil(o.Item) {
		return true
	}

	return false
}

// SetItem gets a reference to the given PlainCountry and assigns it to the Item field.
func (o *EnvelopedPlainCountry) SetItem(v PlainCountry) {
	o.Item = &v
}

func (o EnvelopedPlainCountry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvelopedPlainCountry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Item) {
		toSerialize["item"] = o.Item
	}
	return toSerialize, nil
}

type NullableEnvelopedPlainCountry struct {
	value *EnvelopedPlainCountry
	isSet bool
}

func (v NullableEnvelopedPlainCountry) Get() *EnvelopedPlainCountry {
	return v.value
}

func (v *NullableEnvelopedPlainCountry) Set(val *EnvelopedPlainCountry) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvelopedPlainCountry) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvelopedPlainCountry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvelopedPlainCountry(val *EnvelopedPlainCountry) *NullableEnvelopedPlainCountry {
	return &NullableEnvelopedPlainCountry{value: val, isSet: true}
}

func (v NullableEnvelopedPlainCountry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvelopedPlainCountry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


