/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SolutionObjective type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SolutionObjective{}

// SolutionObjective struct for SolutionObjective
type SolutionObjective struct {
	// At least one character among those allowed: unaccented alpha-numeric characters, \"-\", \".\", \"_\", \"~\", \":\", \"@\", \"!\", \"$\", \",\".
	Name *string `json:"name,omitempty" validate:"regexp=^[a-zA-Z0-9-._~:@!$,]+$"`
	Priority *int32 `json:"priority,omitempty"`
	Direction *OptimizationDirection `json:"direction,omitempty"`
	Value *float32 `json:"value,omitempty"`
}

// NewSolutionObjective instantiates a new SolutionObjective object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSolutionObjective() *SolutionObjective {
	this := SolutionObjective{}
	return &this
}

// NewSolutionObjectiveWithDefaults instantiates a new SolutionObjective object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSolutionObjectiveWithDefaults() *SolutionObjective {
	this := SolutionObjective{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SolutionObjective) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SolutionObjective) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SolutionObjective) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SolutionObjective) SetName(v string) {
	o.Name = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *SolutionObjective) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SolutionObjective) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *SolutionObjective) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *SolutionObjective) SetPriority(v int32) {
	o.Priority = &v
}

// GetDirection returns the Direction field value if set, zero value otherwise.
func (o *SolutionObjective) GetDirection() OptimizationDirection {
	if o == nil || IsNil(o.Direction) {
		var ret OptimizationDirection
		return ret
	}
	return *o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SolutionObjective) GetDirectionOk() (*OptimizationDirection, bool) {
	if o == nil || IsNil(o.Direction) {
		return nil, false
	}
	return o.Direction, true
}

// HasDirection returns a boolean if a field has been set.
func (o *SolutionObjective) HasDirection() bool {
	if o != nil && !IsNil(o.Direction) {
		return true
	}

	return false
}

// SetDirection gets a reference to the given OptimizationDirection and assigns it to the Direction field.
func (o *SolutionObjective) SetDirection(v OptimizationDirection) {
	o.Direction = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *SolutionObjective) GetValue() float32 {
	if o == nil || IsNil(o.Value) {
		var ret float32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SolutionObjective) GetValueOk() (*float32, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *SolutionObjective) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given float32 and assigns it to the Value field.
func (o *SolutionObjective) SetValue(v float32) {
	o.Value = &v
}

func (o SolutionObjective) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SolutionObjective) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.Direction) {
		toSerialize["direction"] = o.Direction
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableSolutionObjective struct {
	value *SolutionObjective
	isSet bool
}

func (v NullableSolutionObjective) Get() *SolutionObjective {
	return v.value
}

func (v *NullableSolutionObjective) Set(val *SolutionObjective) {
	v.value = val
	v.isSet = true
}

func (v NullableSolutionObjective) IsSet() bool {
	return v.isSet
}

func (v *NullableSolutionObjective) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSolutionObjective(val *SolutionObjective) *NullableSolutionObjective {
	return &NullableSolutionObjective{value: val, isSet: true}
}

func (v NullableSolutionObjective) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSolutionObjective) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


