/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// TourViolation - Semantic violations, can be handled \"generically\" or specifically.
type TourViolation struct {
	AtLeastOneConstraintViolation *AtLeastOneConstraintViolation
	AtLeastOneValidCapacityViolation *AtLeastOneValidCapacityViolation
	AuthorizedTimeWindowViolation *AuthorizedTimeWindowViolation
	BeginViolation *BeginViolation
	CapacityViolation *CapacityViolation
	EndViolation *EndViolation
	ForbiddenAssignmentViolation *ForbiddenAssignmentViolation
	MaxDistanceInKmViolation *MaxDistanceInKmViolation
	MaxStopSpanViolation *MaxStopSpanViolation
	MaxStopTagGroupsViolation *MaxStopTagGroupsViolation
	MaxWorkingDurationViolation *MaxWorkingDurationViolation
	OrderViolation *OrderViolation
	RemovalStrategyViolation *RemovalStrategyViolation
	SkillsViolation *SkillsViolation
	StopIncompatibilityViolation *StopIncompatibilityViolation
	SuccessiveStopsViolation *SuccessiveStopsViolation
	WorkingTimeWindowViolation *WorkingTimeWindowViolation
}

// AtLeastOneConstraintViolationAsTourViolation is a convenience function that returns AtLeastOneConstraintViolation wrapped in TourViolation
func AtLeastOneConstraintViolationAsTourViolation(v *AtLeastOneConstraintViolation) TourViolation {
	return TourViolation{
		AtLeastOneConstraintViolation: v,
	}
}

// AtLeastOneValidCapacityViolationAsTourViolation is a convenience function that returns AtLeastOneValidCapacityViolation wrapped in TourViolation
func AtLeastOneValidCapacityViolationAsTourViolation(v *AtLeastOneValidCapacityViolation) TourViolation {
	return TourViolation{
		AtLeastOneValidCapacityViolation: v,
	}
}

// AuthorizedTimeWindowViolationAsTourViolation is a convenience function that returns AuthorizedTimeWindowViolation wrapped in TourViolation
func AuthorizedTimeWindowViolationAsTourViolation(v *AuthorizedTimeWindowViolation) TourViolation {
	return TourViolation{
		AuthorizedTimeWindowViolation: v,
	}
}

// BeginViolationAsTourViolation is a convenience function that returns BeginViolation wrapped in TourViolation
func BeginViolationAsTourViolation(v *BeginViolation) TourViolation {
	return TourViolation{
		BeginViolation: v,
	}
}

// CapacityViolationAsTourViolation is a convenience function that returns CapacityViolation wrapped in TourViolation
func CapacityViolationAsTourViolation(v *CapacityViolation) TourViolation {
	return TourViolation{
		CapacityViolation: v,
	}
}

// EndViolationAsTourViolation is a convenience function that returns EndViolation wrapped in TourViolation
func EndViolationAsTourViolation(v *EndViolation) TourViolation {
	return TourViolation{
		EndViolation: v,
	}
}

// ForbiddenAssignmentViolationAsTourViolation is a convenience function that returns ForbiddenAssignmentViolation wrapped in TourViolation
func ForbiddenAssignmentViolationAsTourViolation(v *ForbiddenAssignmentViolation) TourViolation {
	return TourViolation{
		ForbiddenAssignmentViolation: v,
	}
}

// MaxDistanceInKmViolationAsTourViolation is a convenience function that returns MaxDistanceInKmViolation wrapped in TourViolation
func MaxDistanceInKmViolationAsTourViolation(v *MaxDistanceInKmViolation) TourViolation {
	return TourViolation{
		MaxDistanceInKmViolation: v,
	}
}

// MaxStopSpanViolationAsTourViolation is a convenience function that returns MaxStopSpanViolation wrapped in TourViolation
func MaxStopSpanViolationAsTourViolation(v *MaxStopSpanViolation) TourViolation {
	return TourViolation{
		MaxStopSpanViolation: v,
	}
}

// MaxStopTagGroupsViolationAsTourViolation is a convenience function that returns MaxStopTagGroupsViolation wrapped in TourViolation
func MaxStopTagGroupsViolationAsTourViolation(v *MaxStopTagGroupsViolation) TourViolation {
	return TourViolation{
		MaxStopTagGroupsViolation: v,
	}
}

// MaxWorkingDurationViolationAsTourViolation is a convenience function that returns MaxWorkingDurationViolation wrapped in TourViolation
func MaxWorkingDurationViolationAsTourViolation(v *MaxWorkingDurationViolation) TourViolation {
	return TourViolation{
		MaxWorkingDurationViolation: v,
	}
}

// OrderViolationAsTourViolation is a convenience function that returns OrderViolation wrapped in TourViolation
func OrderViolationAsTourViolation(v *OrderViolation) TourViolation {
	return TourViolation{
		OrderViolation: v,
	}
}

// RemovalStrategyViolationAsTourViolation is a convenience function that returns RemovalStrategyViolation wrapped in TourViolation
func RemovalStrategyViolationAsTourViolation(v *RemovalStrategyViolation) TourViolation {
	return TourViolation{
		RemovalStrategyViolation: v,
	}
}

// SkillsViolationAsTourViolation is a convenience function that returns SkillsViolation wrapped in TourViolation
func SkillsViolationAsTourViolation(v *SkillsViolation) TourViolation {
	return TourViolation{
		SkillsViolation: v,
	}
}

// StopIncompatibilityViolationAsTourViolation is a convenience function that returns StopIncompatibilityViolation wrapped in TourViolation
func StopIncompatibilityViolationAsTourViolation(v *StopIncompatibilityViolation) TourViolation {
	return TourViolation{
		StopIncompatibilityViolation: v,
	}
}

// SuccessiveStopsViolationAsTourViolation is a convenience function that returns SuccessiveStopsViolation wrapped in TourViolation
func SuccessiveStopsViolationAsTourViolation(v *SuccessiveStopsViolation) TourViolation {
	return TourViolation{
		SuccessiveStopsViolation: v,
	}
}

// WorkingTimeWindowViolationAsTourViolation is a convenience function that returns WorkingTimeWindowViolation wrapped in TourViolation
func WorkingTimeWindowViolationAsTourViolation(v *WorkingTimeWindowViolation) TourViolation {
	return TourViolation{
		WorkingTimeWindowViolation: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *TourViolation) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AtLeastOneConstraintViolation
	err = newStrictDecoder(data).Decode(&dst.AtLeastOneConstraintViolation)
	if err == nil {
		jsonAtLeastOneConstraintViolation, _ := json.Marshal(dst.AtLeastOneConstraintViolation)
		if string(jsonAtLeastOneConstraintViolation) == "{}" { // empty struct
			dst.AtLeastOneConstraintViolation = nil
		} else {
			if err = validator.Validate(dst.AtLeastOneConstraintViolation); err != nil {
				dst.AtLeastOneConstraintViolation = nil
			} else {
				match++
			}
		}
	} else {
		dst.AtLeastOneConstraintViolation = nil
	}

	// try to unmarshal data into AtLeastOneValidCapacityViolation
	err = newStrictDecoder(data).Decode(&dst.AtLeastOneValidCapacityViolation)
	if err == nil {
		jsonAtLeastOneValidCapacityViolation, _ := json.Marshal(dst.AtLeastOneValidCapacityViolation)
		if string(jsonAtLeastOneValidCapacityViolation) == "{}" { // empty struct
			dst.AtLeastOneValidCapacityViolation = nil
		} else {
			if err = validator.Validate(dst.AtLeastOneValidCapacityViolation); err != nil {
				dst.AtLeastOneValidCapacityViolation = nil
			} else {
				match++
			}
		}
	} else {
		dst.AtLeastOneValidCapacityViolation = nil
	}

	// try to unmarshal data into AuthorizedTimeWindowViolation
	err = newStrictDecoder(data).Decode(&dst.AuthorizedTimeWindowViolation)
	if err == nil {
		jsonAuthorizedTimeWindowViolation, _ := json.Marshal(dst.AuthorizedTimeWindowViolation)
		if string(jsonAuthorizedTimeWindowViolation) == "{}" { // empty struct
			dst.AuthorizedTimeWindowViolation = nil
		} else {
			if err = validator.Validate(dst.AuthorizedTimeWindowViolation); err != nil {
				dst.AuthorizedTimeWindowViolation = nil
			} else {
				match++
			}
		}
	} else {
		dst.AuthorizedTimeWindowViolation = nil
	}

	// try to unmarshal data into BeginViolation
	err = newStrictDecoder(data).Decode(&dst.BeginViolation)
	if err == nil {
		jsonBeginViolation, _ := json.Marshal(dst.BeginViolation)
		if string(jsonBeginViolation) == "{}" { // empty struct
			dst.BeginViolation = nil
		} else {
			if err = validator.Validate(dst.BeginViolation); err != nil {
				dst.BeginViolation = nil
			} else {
				match++
			}
		}
	} else {
		dst.BeginViolation = nil
	}

	// try to unmarshal data into CapacityViolation
	err = newStrictDecoder(data).Decode(&dst.CapacityViolation)
	if err == nil {
		jsonCapacityViolation, _ := json.Marshal(dst.CapacityViolation)
		if string(jsonCapacityViolation) == "{}" { // empty struct
			dst.CapacityViolation = nil
		} else {
			if err = validator.Validate(dst.CapacityViolation); err != nil {
				dst.CapacityViolation = nil
			} else {
				match++
			}
		}
	} else {
		dst.CapacityViolation = nil
	}

	// try to unmarshal data into EndViolation
	err = newStrictDecoder(data).Decode(&dst.EndViolation)
	if err == nil {
		jsonEndViolation, _ := json.Marshal(dst.EndViolation)
		if string(jsonEndViolation) == "{}" { // empty struct
			dst.EndViolation = nil
		} else {
			if err = validator.Validate(dst.EndViolation); err != nil {
				dst.EndViolation = nil
			} else {
				match++
			}
		}
	} else {
		dst.EndViolation = nil
	}

	// try to unmarshal data into ForbiddenAssignmentViolation
	err = newStrictDecoder(data).Decode(&dst.ForbiddenAssignmentViolation)
	if err == nil {
		jsonForbiddenAssignmentViolation, _ := json.Marshal(dst.ForbiddenAssignmentViolation)
		if string(jsonForbiddenAssignmentViolation) == "{}" { // empty struct
			dst.ForbiddenAssignmentViolation = nil
		} else {
			if err = validator.Validate(dst.ForbiddenAssignmentViolation); err != nil {
				dst.ForbiddenAssignmentViolation = nil
			} else {
				match++
			}
		}
	} else {
		dst.ForbiddenAssignmentViolation = nil
	}

	// try to unmarshal data into MaxDistanceInKmViolation
	err = newStrictDecoder(data).Decode(&dst.MaxDistanceInKmViolation)
	if err == nil {
		jsonMaxDistanceInKmViolation, _ := json.Marshal(dst.MaxDistanceInKmViolation)
		if string(jsonMaxDistanceInKmViolation) == "{}" { // empty struct
			dst.MaxDistanceInKmViolation = nil
		} else {
			if err = validator.Validate(dst.MaxDistanceInKmViolation); err != nil {
				dst.MaxDistanceInKmViolation = nil
			} else {
				match++
			}
		}
	} else {
		dst.MaxDistanceInKmViolation = nil
	}

	// try to unmarshal data into MaxStopSpanViolation
	err = newStrictDecoder(data).Decode(&dst.MaxStopSpanViolation)
	if err == nil {
		jsonMaxStopSpanViolation, _ := json.Marshal(dst.MaxStopSpanViolation)
		if string(jsonMaxStopSpanViolation) == "{}" { // empty struct
			dst.MaxStopSpanViolation = nil
		} else {
			if err = validator.Validate(dst.MaxStopSpanViolation); err != nil {
				dst.MaxStopSpanViolation = nil
			} else {
				match++
			}
		}
	} else {
		dst.MaxStopSpanViolation = nil
	}

	// try to unmarshal data into MaxStopTagGroupsViolation
	err = newStrictDecoder(data).Decode(&dst.MaxStopTagGroupsViolation)
	if err == nil {
		jsonMaxStopTagGroupsViolation, _ := json.Marshal(dst.MaxStopTagGroupsViolation)
		if string(jsonMaxStopTagGroupsViolation) == "{}" { // empty struct
			dst.MaxStopTagGroupsViolation = nil
		} else {
			if err = validator.Validate(dst.MaxStopTagGroupsViolation); err != nil {
				dst.MaxStopTagGroupsViolation = nil
			} else {
				match++
			}
		}
	} else {
		dst.MaxStopTagGroupsViolation = nil
	}

	// try to unmarshal data into MaxWorkingDurationViolation
	err = newStrictDecoder(data).Decode(&dst.MaxWorkingDurationViolation)
	if err == nil {
		jsonMaxWorkingDurationViolation, _ := json.Marshal(dst.MaxWorkingDurationViolation)
		if string(jsonMaxWorkingDurationViolation) == "{}" { // empty struct
			dst.MaxWorkingDurationViolation = nil
		} else {
			if err = validator.Validate(dst.MaxWorkingDurationViolation); err != nil {
				dst.MaxWorkingDurationViolation = nil
			} else {
				match++
			}
		}
	} else {
		dst.MaxWorkingDurationViolation = nil
	}

	// try to unmarshal data into OrderViolation
	err = newStrictDecoder(data).Decode(&dst.OrderViolation)
	if err == nil {
		jsonOrderViolation, _ := json.Marshal(dst.OrderViolation)
		if string(jsonOrderViolation) == "{}" { // empty struct
			dst.OrderViolation = nil
		} else {
			if err = validator.Validate(dst.OrderViolation); err != nil {
				dst.OrderViolation = nil
			} else {
				match++
			}
		}
	} else {
		dst.OrderViolation = nil
	}

	// try to unmarshal data into RemovalStrategyViolation
	err = newStrictDecoder(data).Decode(&dst.RemovalStrategyViolation)
	if err == nil {
		jsonRemovalStrategyViolation, _ := json.Marshal(dst.RemovalStrategyViolation)
		if string(jsonRemovalStrategyViolation) == "{}" { // empty struct
			dst.RemovalStrategyViolation = nil
		} else {
			if err = validator.Validate(dst.RemovalStrategyViolation); err != nil {
				dst.RemovalStrategyViolation = nil
			} else {
				match++
			}
		}
	} else {
		dst.RemovalStrategyViolation = nil
	}

	// try to unmarshal data into SkillsViolation
	err = newStrictDecoder(data).Decode(&dst.SkillsViolation)
	if err == nil {
		jsonSkillsViolation, _ := json.Marshal(dst.SkillsViolation)
		if string(jsonSkillsViolation) == "{}" { // empty struct
			dst.SkillsViolation = nil
		} else {
			if err = validator.Validate(dst.SkillsViolation); err != nil {
				dst.SkillsViolation = nil
			} else {
				match++
			}
		}
	} else {
		dst.SkillsViolation = nil
	}

	// try to unmarshal data into StopIncompatibilityViolation
	err = newStrictDecoder(data).Decode(&dst.StopIncompatibilityViolation)
	if err == nil {
		jsonStopIncompatibilityViolation, _ := json.Marshal(dst.StopIncompatibilityViolation)
		if string(jsonStopIncompatibilityViolation) == "{}" { // empty struct
			dst.StopIncompatibilityViolation = nil
		} else {
			if err = validator.Validate(dst.StopIncompatibilityViolation); err != nil {
				dst.StopIncompatibilityViolation = nil
			} else {
				match++
			}
		}
	} else {
		dst.StopIncompatibilityViolation = nil
	}

	// try to unmarshal data into SuccessiveStopsViolation
	err = newStrictDecoder(data).Decode(&dst.SuccessiveStopsViolation)
	if err == nil {
		jsonSuccessiveStopsViolation, _ := json.Marshal(dst.SuccessiveStopsViolation)
		if string(jsonSuccessiveStopsViolation) == "{}" { // empty struct
			dst.SuccessiveStopsViolation = nil
		} else {
			if err = validator.Validate(dst.SuccessiveStopsViolation); err != nil {
				dst.SuccessiveStopsViolation = nil
			} else {
				match++
			}
		}
	} else {
		dst.SuccessiveStopsViolation = nil
	}

	// try to unmarshal data into WorkingTimeWindowViolation
	err = newStrictDecoder(data).Decode(&dst.WorkingTimeWindowViolation)
	if err == nil {
		jsonWorkingTimeWindowViolation, _ := json.Marshal(dst.WorkingTimeWindowViolation)
		if string(jsonWorkingTimeWindowViolation) == "{}" { // empty struct
			dst.WorkingTimeWindowViolation = nil
		} else {
			if err = validator.Validate(dst.WorkingTimeWindowViolation); err != nil {
				dst.WorkingTimeWindowViolation = nil
			} else {
				match++
			}
		}
	} else {
		dst.WorkingTimeWindowViolation = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AtLeastOneConstraintViolation = nil
		dst.AtLeastOneValidCapacityViolation = nil
		dst.AuthorizedTimeWindowViolation = nil
		dst.BeginViolation = nil
		dst.CapacityViolation = nil
		dst.EndViolation = nil
		dst.ForbiddenAssignmentViolation = nil
		dst.MaxDistanceInKmViolation = nil
		dst.MaxStopSpanViolation = nil
		dst.MaxStopTagGroupsViolation = nil
		dst.MaxWorkingDurationViolation = nil
		dst.OrderViolation = nil
		dst.RemovalStrategyViolation = nil
		dst.SkillsViolation = nil
		dst.StopIncompatibilityViolation = nil
		dst.SuccessiveStopsViolation = nil
		dst.WorkingTimeWindowViolation = nil

		return fmt.Errorf("data matches more than one schema in oneOf(TourViolation)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(TourViolation)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TourViolation) MarshalJSON() ([]byte, error) {
	if src.AtLeastOneConstraintViolation != nil {
		return json.Marshal(&src.AtLeastOneConstraintViolation)
	}

	if src.AtLeastOneValidCapacityViolation != nil {
		return json.Marshal(&src.AtLeastOneValidCapacityViolation)
	}

	if src.AuthorizedTimeWindowViolation != nil {
		return json.Marshal(&src.AuthorizedTimeWindowViolation)
	}

	if src.BeginViolation != nil {
		return json.Marshal(&src.BeginViolation)
	}

	if src.CapacityViolation != nil {
		return json.Marshal(&src.CapacityViolation)
	}

	if src.EndViolation != nil {
		return json.Marshal(&src.EndViolation)
	}

	if src.ForbiddenAssignmentViolation != nil {
		return json.Marshal(&src.ForbiddenAssignmentViolation)
	}

	if src.MaxDistanceInKmViolation != nil {
		return json.Marshal(&src.MaxDistanceInKmViolation)
	}

	if src.MaxStopSpanViolation != nil {
		return json.Marshal(&src.MaxStopSpanViolation)
	}

	if src.MaxStopTagGroupsViolation != nil {
		return json.Marshal(&src.MaxStopTagGroupsViolation)
	}

	if src.MaxWorkingDurationViolation != nil {
		return json.Marshal(&src.MaxWorkingDurationViolation)
	}

	if src.OrderViolation != nil {
		return json.Marshal(&src.OrderViolation)
	}

	if src.RemovalStrategyViolation != nil {
		return json.Marshal(&src.RemovalStrategyViolation)
	}

	if src.SkillsViolation != nil {
		return json.Marshal(&src.SkillsViolation)
	}

	if src.StopIncompatibilityViolation != nil {
		return json.Marshal(&src.StopIncompatibilityViolation)
	}

	if src.SuccessiveStopsViolation != nil {
		return json.Marshal(&src.SuccessiveStopsViolation)
	}

	if src.WorkingTimeWindowViolation != nil {
		return json.Marshal(&src.WorkingTimeWindowViolation)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *TourViolation) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.AtLeastOneConstraintViolation != nil {
		return obj.AtLeastOneConstraintViolation
	}

	if obj.AtLeastOneValidCapacityViolation != nil {
		return obj.AtLeastOneValidCapacityViolation
	}

	if obj.AuthorizedTimeWindowViolation != nil {
		return obj.AuthorizedTimeWindowViolation
	}

	if obj.BeginViolation != nil {
		return obj.BeginViolation
	}

	if obj.CapacityViolation != nil {
		return obj.CapacityViolation
	}

	if obj.EndViolation != nil {
		return obj.EndViolation
	}

	if obj.ForbiddenAssignmentViolation != nil {
		return obj.ForbiddenAssignmentViolation
	}

	if obj.MaxDistanceInKmViolation != nil {
		return obj.MaxDistanceInKmViolation
	}

	if obj.MaxStopSpanViolation != nil {
		return obj.MaxStopSpanViolation
	}

	if obj.MaxStopTagGroupsViolation != nil {
		return obj.MaxStopTagGroupsViolation
	}

	if obj.MaxWorkingDurationViolation != nil {
		return obj.MaxWorkingDurationViolation
	}

	if obj.OrderViolation != nil {
		return obj.OrderViolation
	}

	if obj.RemovalStrategyViolation != nil {
		return obj.RemovalStrategyViolation
	}

	if obj.SkillsViolation != nil {
		return obj.SkillsViolation
	}

	if obj.StopIncompatibilityViolation != nil {
		return obj.StopIncompatibilityViolation
	}

	if obj.SuccessiveStopsViolation != nil {
		return obj.SuccessiveStopsViolation
	}

	if obj.WorkingTimeWindowViolation != nil {
		return obj.WorkingTimeWindowViolation
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj TourViolation) GetActualInstanceValue() (interface{}) {
	if obj.AtLeastOneConstraintViolation != nil {
		return *obj.AtLeastOneConstraintViolation
	}

	if obj.AtLeastOneValidCapacityViolation != nil {
		return *obj.AtLeastOneValidCapacityViolation
	}

	if obj.AuthorizedTimeWindowViolation != nil {
		return *obj.AuthorizedTimeWindowViolation
	}

	if obj.BeginViolation != nil {
		return *obj.BeginViolation
	}

	if obj.CapacityViolation != nil {
		return *obj.CapacityViolation
	}

	if obj.EndViolation != nil {
		return *obj.EndViolation
	}

	if obj.ForbiddenAssignmentViolation != nil {
		return *obj.ForbiddenAssignmentViolation
	}

	if obj.MaxDistanceInKmViolation != nil {
		return *obj.MaxDistanceInKmViolation
	}

	if obj.MaxStopSpanViolation != nil {
		return *obj.MaxStopSpanViolation
	}

	if obj.MaxStopTagGroupsViolation != nil {
		return *obj.MaxStopTagGroupsViolation
	}

	if obj.MaxWorkingDurationViolation != nil {
		return *obj.MaxWorkingDurationViolation
	}

	if obj.OrderViolation != nil {
		return *obj.OrderViolation
	}

	if obj.RemovalStrategyViolation != nil {
		return *obj.RemovalStrategyViolation
	}

	if obj.SkillsViolation != nil {
		return *obj.SkillsViolation
	}

	if obj.StopIncompatibilityViolation != nil {
		return *obj.StopIncompatibilityViolation
	}

	if obj.SuccessiveStopsViolation != nil {
		return *obj.SuccessiveStopsViolation
	}

	if obj.WorkingTimeWindowViolation != nil {
		return *obj.WorkingTimeWindowViolation
	}

	// all schemas are nil
	return nil
}

type NullableTourViolation struct {
	value *TourViolation
	isSet bool
}

func (v NullableTourViolation) Get() *TourViolation {
	return v.value
}

func (v *NullableTourViolation) Set(val *TourViolation) {
	v.value = val
	v.isSet = true
}

func (v NullableTourViolation) IsSet() bool {
	return v.isSet
}

func (v *NullableTourViolation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTourViolation(val *TourViolation) *NullableTourViolation {
	return &NullableTourViolation{value: val, isSet: true}
}

func (v NullableTourViolation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTourViolation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


