/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MFAConfigRequestSMS type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MFAConfigRequestSMS{}

// MFAConfigRequestSMS A request to update or disable the OTP type \"sms\" in the user's MFA configuration.
type MFAConfigRequestSMS struct {
	OtpType string `json:"otpType"`
	// Phone number in E.164 international format (e.g., +33612345678).
	PhoneNumber string `json:"phoneNumber" validate:"regexp=^\\\\+[1-9]\\\\d{1,14}$"`
	Password Password `json:"password"`
}

type _MFAConfigRequestSMS MFAConfigRequestSMS

// NewMFAConfigRequestSMS instantiates a new MFAConfigRequestSMS object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMFAConfigRequestSMS(otpType string, phoneNumber string, password Password) *MFAConfigRequestSMS {
	this := MFAConfigRequestSMS{}
	this.OtpType = otpType
	this.PhoneNumber = phoneNumber
	this.Password = password
	return &this
}

// NewMFAConfigRequestSMSWithDefaults instantiates a new MFAConfigRequestSMS object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMFAConfigRequestSMSWithDefaults() *MFAConfigRequestSMS {
	this := MFAConfigRequestSMS{}
	return &this
}

// GetOtpType returns the OtpType field value
func (o *MFAConfigRequestSMS) GetOtpType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OtpType
}

// GetOtpTypeOk returns a tuple with the OtpType field value
// and a boolean to check if the value has been set.
func (o *MFAConfigRequestSMS) GetOtpTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OtpType, true
}

// SetOtpType sets field value
func (o *MFAConfigRequestSMS) SetOtpType(v string) {
	o.OtpType = v
}

// GetPhoneNumber returns the PhoneNumber field value
func (o *MFAConfigRequestSMS) GetPhoneNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value
// and a boolean to check if the value has been set.
func (o *MFAConfigRequestSMS) GetPhoneNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhoneNumber, true
}

// SetPhoneNumber sets field value
func (o *MFAConfigRequestSMS) SetPhoneNumber(v string) {
	o.PhoneNumber = v
}

// GetPassword returns the Password field value
func (o *MFAConfigRequestSMS) GetPassword() Password {
	if o == nil {
		var ret Password
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *MFAConfigRequestSMS) GetPasswordOk() (*Password, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *MFAConfigRequestSMS) SetPassword(v Password) {
	o.Password = v
}

func (o MFAConfigRequestSMS) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MFAConfigRequestSMS) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["otpType"] = o.OtpType
	toSerialize["phoneNumber"] = o.PhoneNumber
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *MFAConfigRequestSMS) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"otpType",
		"phoneNumber",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMFAConfigRequestSMS := _MFAConfigRequestSMS{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMFAConfigRequestSMS)

	if err != nil {
		return err
	}

	*o = MFAConfigRequestSMS(varMFAConfigRequestSMS)

	return err
}

type NullableMFAConfigRequestSMS struct {
	value *MFAConfigRequestSMS
	isSet bool
}

func (v NullableMFAConfigRequestSMS) Get() *MFAConfigRequestSMS {
	return v.value
}

func (v *NullableMFAConfigRequestSMS) Set(val *MFAConfigRequestSMS) {
	v.value = val
	v.isSet = true
}

func (v NullableMFAConfigRequestSMS) IsSet() bool {
	return v.isSet
}

func (v *NullableMFAConfigRequestSMS) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMFAConfigRequestSMS(val *MFAConfigRequestSMS) *NullableMFAConfigRequestSMS {
	return &NullableMFAConfigRequestSMS{value: val, isSet: true}
}

func (v NullableMFAConfigRequestSMS) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMFAConfigRequestSMS) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


