/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Password type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Password{}

// Password A user password must contain at least: - 1 number, - 1 uppercase letter, - 1 lowercase letter, - 1 special character amongst the following:   !\"#$%&'()*+,-./:;<=>?@[]^_`{|}~ - 12 characters. And it must not exceed 72 bytes. 
type Password struct {
}

// NewPassword instantiates a new Password object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPassword() *Password {
	this := Password{}
	return &this
}

// NewPasswordWithDefaults instantiates a new Password object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPasswordWithDefaults() *Password {
	this := Password{}
	return &this
}

func (o Password) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Password) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullablePassword struct {
	value *Password
	isSet bool
}

func (v NullablePassword) Get() *Password {
	return v.value
}

func (v *NullablePassword) Set(val *Password) {
	v.value = val
	v.isSet = true
}

func (v NullablePassword) IsSet() bool {
	return v.isSet
}

func (v *NullablePassword) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePassword(val *Password) *NullablePassword {
	return &NullablePassword{value: val, isSet: true}
}

func (v NullablePassword) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePassword) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


