/*
Kardinal ARO API

This document specifies the REST API of Kardinal ARO v2.

API version: 2.45.0
Contact: contact@kardinal.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EnvelopedLoginMFAOutputItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvelopedLoginMFAOutputItem{}

// EnvelopedLoginMFAOutputItem struct for EnvelopedLoginMFAOutputItem
type EnvelopedLoginMFAOutputItem struct {
	// A JSON Web Token with scope 'mfa', to be used to setup MFA authentication, valid for 1 hour.
	MfaToken *string `json:"mfaToken,omitempty"`
}

// NewEnvelopedLoginMFAOutputItem instantiates a new EnvelopedLoginMFAOutputItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvelopedLoginMFAOutputItem() *EnvelopedLoginMFAOutputItem {
	this := EnvelopedLoginMFAOutputItem{}
	return &this
}

// NewEnvelopedLoginMFAOutputItemWithDefaults instantiates a new EnvelopedLoginMFAOutputItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvelopedLoginMFAOutputItemWithDefaults() *EnvelopedLoginMFAOutputItem {
	this := EnvelopedLoginMFAOutputItem{}
	return &this
}

// GetMfaToken returns the MfaToken field value if set, zero value otherwise.
func (o *EnvelopedLoginMFAOutputItem) GetMfaToken() string {
	if o == nil || IsNil(o.MfaToken) {
		var ret string
		return ret
	}
	return *o.MfaToken
}

// GetMfaTokenOk returns a tuple with the MfaToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvelopedLoginMFAOutputItem) GetMfaTokenOk() (*string, bool) {
	if o == nil || IsNil(o.MfaToken) {
		return nil, false
	}
	return o.MfaToken, true
}

// HasMfaToken returns a boolean if a field has been set.
func (o *EnvelopedLoginMFAOutputItem) HasMfaToken() bool {
	if o != nil && !IsNil(o.MfaToken) {
		return true
	}

	return false
}

// SetMfaToken gets a reference to the given string and assigns it to the MfaToken field.
func (o *EnvelopedLoginMFAOutputItem) SetMfaToken(v string) {
	o.MfaToken = &v
}

func (o EnvelopedLoginMFAOutputItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvelopedLoginMFAOutputItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MfaToken) {
		toSerialize["mfaToken"] = o.MfaToken
	}
	return toSerialize, nil
}

type NullableEnvelopedLoginMFAOutputItem struct {
	value *EnvelopedLoginMFAOutputItem
	isSet bool
}

func (v NullableEnvelopedLoginMFAOutputItem) Get() *EnvelopedLoginMFAOutputItem {
	return v.value
}

func (v *NullableEnvelopedLoginMFAOutputItem) Set(val *EnvelopedLoginMFAOutputItem) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvelopedLoginMFAOutputItem) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvelopedLoginMFAOutputItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvelopedLoginMFAOutputItem(val *EnvelopedLoginMFAOutputItem) *NullableEnvelopedLoginMFAOutputItem {
	return &NullableEnvelopedLoginMFAOutputItem{value: val, isSet: true}
}

func (v NullableEnvelopedLoginMFAOutputItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvelopedLoginMFAOutputItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


